-- AUTO-GENERATED by scripts/gen-content.mjs — aged_domains seed data.
-- Safe to re-run: clears existing seed rows by domain before inserting.
delete from public.hitam_aged_domains
where domain in ('depositmaxwin.com', 'jackpotgacor.net', 'rajahokislot.com', 'winrate88arena.org', 'pinjamancepatku.id', 'kreditdanapro.com', 'modalusahaku.co', 'investcerdas.id', 'sehatalami.id', 'healthvitalpro.com', 'klinikgizi.org', 'cryptocuanid.com', 'blockchainhub.net', 'tokenmasadepan.com', 'jelajahnusantara.id', 'luxurytraveldeals.com', 'backpackerasia.net', 'belajarpintar.id', 'onlinecourseshub.com', 'kampusdigital.org', 'gayastylehits.com', 'trendwearstore.com', 'koleksibusana.id', 'otomotifmania.com', 'autopartspro.net', 'bengkelmodif.id', 'propertiprima.id', 'realestatevault.com', 'hunianidaman.com', 'beritaterkini.id', 'dailyinsightnews.com', 'infoharian.org', 'kabarupdate.net', 'globalmarketwire.com');

insert into public.hitam_aged_domains
  (domain, tld, da, pa, dr, ur, tf, cf, age_years, referring_domains, backlinks, spam_score, niche, language, price_idr, status, highlight)
values
  ('depositmaxwin.com', 'com', 58, 52, 61, 48, 34, 41, 11, 1450, 28600, 7, 'gambling/slot', 'id', 42000000, 'available', 'Domain slot DA 58 dengan profil backlink kasino matang siap dipasang 301 instan.'),
  ('jackpotgacor.net', 'net', 44, 39, 47, 36, 27, 33, 8, 780, 15400, 9, 'gambling/slot', 'id', 21500000, 'available', 'Backlink judi padat dan anchor relevan, cocok jadi tameng utama jaringan PBN kamu.'),
  ('rajahokislot.com', 'com', 36, 31, 38, 29, 22, 28, 6, 410, 7200, 12, 'gambling/slot', 'id', 12500000, 'reserved', 'Aged 6 tahun dengan histori ranking slot, langsung tancap gas tanpa sandbox lama.'),
  ('winrate88arena.org', 'org', 29, 25, 31, 24, 18, 24, 5, 230, 3900, 11, 'gambling/slot', 'id', 6800000, 'available', 'Entry-level untuk uji ceruk slot tanpa bakar budget besar di awal.'),
  ('pinjamancepatku.id', 'id', 41, 36, 43, 34, 29, 32, 7, 520, 9800, 6, 'finance/pinjaman', 'id', 18500000, 'available', 'TLD .id otoritatif untuk niche pinjaman lokal, trust signal kuat di SERP Indonesia.'),
  ('kreditdanapro.com', 'com', 47, 42, 49, 40, 31, 36, 9, 910, 17300, 5, 'finance/pinjaman', 'id', 24000000, 'available', 'Profil finance bersih spam-score 5, ideal untuk money site pinjaman jangka panjang.'),
  ('modalusahaku.co', 'co', 33, 28, 35, 27, 20, 26, 6, 340, 5600, 8, 'finance/pinjaman', 'id', 9500000, 'sold', 'Nama brandable untuk fintech modal usaha, sayang sudah terjual cepat.'),
  ('investcerdas.id', 'id', 38, 33, 40, 31, 26, 30, 8, 480, 8100, 4, 'finance/pinjaman', 'id', 15500000, 'available', 'Domain investasi lokal clean, anchor natural ke topik keuangan personal.'),
  ('sehatalami.id', 'id', 35, 30, 36, 28, 24, 29, 7, 390, 6400, 5, 'health', 'id', 11500000, 'available', 'Niche kesehatan herbal dengan trust .id, aman untuk affiliate produk lokal.'),
  ('healthvitalpro.com', 'com', 51, 45, 53, 43, 33, 38, 12, 1120, 22800, 6, 'health', 'en', 31000000, 'available', 'DA 51 health authority internasional, RD 1.120 siap dorong niche supplement global.'),
  ('klinikgizi.org', 'org', 27, 23, 29, 22, 17, 23, 5, 190, 2800, 9, 'health', 'id', 5400000, 'available', 'Domain .org bertema klinik gizi, cocok untuk konten edukasi kesehatan.'),
  ('cryptocuanid.com', 'com', 43, 38, 45, 36, 28, 34, 7, 640, 13200, 10, 'crypto', 'id', 19500000, 'available', 'Aged crypto Indonesia dengan momentum backlink exchange dan media kripto lokal.'),
  ('blockchainhub.net', 'net', 54, 48, 56, 45, 36, 40, 13, 1680, 34500, 7, 'crypto', 'en', 38000000, 'reserved', 'Aged 13 tahun, RD 1.680 dari ekosistem blockchain global, otoritas kelas berat.'),
  ('tokenmasadepan.com', 'com', 31, 27, 33, 26, 21, 27, 5, 280, 4700, 13, 'crypto', 'id', 7900000, 'available', 'Domain kripto fresh-aged untuk landing presale token, harga ramah pemula.'),
  ('jelajahnusantara.id', 'id', 40, 35, 42, 33, 27, 31, 9, 560, 9200, 3, 'travel', 'id', 16500000, 'available', 'Travel lokal spam-score 3, backlink dari media wisata dan blog perjalanan.'),
  ('luxurytraveldeals.com', 'com', 56, 50, 58, 47, 38, 42, 14, 1920, 41200, 5, 'travel', 'en', 45000000, 'available', 'DA 56 travel premium, RD hampir 2.000 dari outlet perjalanan tier-1 dunia.'),
  ('backpackerasia.net', 'net', 34, 29, 36, 28, 23, 28, 7, 360, 5900, 6, 'travel', 'en', 10500000, 'sold', 'Domain backpacking Asia yang sudah laku, bukti niche travel tetap diburu.'),
  ('belajarpintar.id', 'id', 37, 32, 39, 31, 25, 30, 8, 450, 7100, 4, 'edukasi', 'id', 13500000, 'available', 'Domain edukasi .id bersih, kuat untuk platform kursus dan bimbel online.'),
  ('onlinecourseshub.com', 'com', 49, 44, 51, 42, 32, 37, 11, 980, 19600, 5, 'edukasi', 'en', 26000000, 'available', 'Aged 11 tahun bertema e-learning, link dari domain pendidikan berotoritas.'),
  ('kampusdigital.org', 'org', 26, 22, 28, 21, 16, 22, 5, 160, 2400, 7, 'edukasi', 'id', 4600000, 'available', 'Entry-level edukasi .org untuk uji konten dan funnel kelas online.'),
  ('gayastylehits.com', 'com', 39, 34, 41, 32, 26, 31, 8, 510, 8800, 8, 'fashion', 'id', 14500000, 'available', 'Domain fashion dengan backlink lifestyle, pas untuk toko busana dan affiliate.'),
  ('trendwearstore.com', 'com', 45, 40, 47, 38, 30, 35, 10, 720, 14100, 6, 'fashion', 'en', 20500000, 'reserved', 'Aged fashion global DA 45, anchor produk apparel siap dukung dropship skala.'),
  ('koleksibusana.id', 'id', 28, 24, 30, 23, 18, 24, 6, 210, 3300, 9, 'fashion', 'id', 5800000, 'available', 'TLD .id bertema busana lokal, murah meriah untuk katalog fashion baru.'),
  ('otomotifmania.com', 'com', 42, 37, 44, 35, 28, 33, 9, 600, 11200, 7, 'otomotif', 'id', 17500000, 'available', 'Komunitas otomotif aged, backlink dari forum dan media mobil Indonesia.'),
  ('autopartspro.net', 'net', 50, 45, 52, 43, 34, 39, 12, 1050, 23700, 5, 'otomotif', 'en', 28500000, 'available', 'DA 50 spare-part global, RD 1.050 ideal untuk toko sparepart e-commerce.'),
  ('bengkelmodif.id', 'id', 24, 20, 26, 19, 15, 21, 4, 120, 1700, 10, 'otomotif', 'id', 3400000, 'available', 'Aged 4 tahun bertema bengkel modifikasi, starter murah untuk niche otomotif.'),
  ('propertiprima.id', 'id', 46, 41, 48, 39, 31, 36, 10, 830, 16200, 4, 'properti', 'id', 23000000, 'available', 'Domain properti .id otoritas tinggi, trust kuat untuk listing rumah dan ruko.'),
  ('realestatevault.com', 'com', 60, 54, 63, 51, 40, 44, 16, 2400, 52000, 4, 'properti', 'en', 48000000, 'available', 'Flagship DA 60, aged 16 tahun, RD 2.400 dari portal properti kelas dunia.'),
  ('hunianidaman.com', 'com', 32, 28, 34, 27, 22, 27, 6, 300, 4900, 8, 'properti', 'id', 8500000, 'sold', 'Domain hunian lokal yang cepat ludes, indikasi permintaan properti tinggi.'),
  ('beritaterkini.id', 'id', 52, 47, 54, 44, 35, 40, 13, 1380, 29800, 6, 'general/news', 'id', 33000000, 'available', 'Portal berita aged 13 tahun, RD 1.380 dari media nasional, otoritas serbaguna.'),
  ('dailyinsightnews.com', 'com', 62, 56, 64, 52, 41, 45, 18, 2850, 61500, 3, 'general/news', 'en', 47500000, 'reserved', 'Aged 18 tahun, DA 62, RD 2.850 super clean — fondasi otoritas paling kuat di katalog.'),
  ('infoharian.org', 'org', 30, 26, 32, 25, 20, 26, 7, 260, 4100, 11, 'general/news', 'id', 6200000, 'available', 'Domain berita .org serbaguna, fleksibel untuk konten campuran dan link tier-2.'),
  ('kabarupdate.net', 'net', 22, 18, 24, 17, 14, 20, 4, 90, 1200, 13, 'general/news', 'id', 2100000, 'available', 'Termurah di katalog, aged 4 tahun cocok untuk eksperimen jaringan tier-3.'),
  ('globalmarketwire.com', 'com', 55, 49, 57, 46, 37, 41, 15, 2050, 44800, 5, 'finance/pinjaman', 'en', 40000000, 'available', 'Aged 15 tahun bertema finance global, RD 2.050 untuk money site kelas berat.');
