//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  blog: Blog;
  blogConnection: BlogConnection;
  niche: Niche;
  nicheConnection: NicheConnection;
  service: Service;
  serviceConnection: ServiceConnection;
  testimonial: Testimonial;
  testimonialConnection: TestimonialConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBlogConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
};


export type QueryNicheArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNicheConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NicheFilter>;
};


export type QueryServiceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
};


export type QueryTestimonialArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
};

export type DocumentFilter = {
  blog?: InputMaybe<BlogFilter>;
  niche?: InputMaybe<NicheFilter>;
  service?: InputMaybe<ServiceFilter>;
  testimonial?: InputMaybe<TestimonialFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Blog | Niche | Service | Testimonial | Folder;

export type Blog = Node & Document & {
  __typename?: 'Blog';
  title: Scalars['String']['output'];
  excerpt: Scalars['String']['output'];
  date: Scalars['String']['output'];
  author: Scalars['String']['output'];
  cover?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  category?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  cover?: InputMaybe<ImageFilter>;
  tags?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type BlogConnectionEdges = {
  __typename?: 'BlogConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Blog>;
};

export type BlogConnection = Connection & {
  __typename?: 'BlogConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BlogConnectionEdges>>>;
};

export type NicheHero = {
  __typename?: 'NicheHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type NicheStats = {
  __typename?: 'NicheStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type NichePainPoints = {
  __typename?: 'NichePainPoints';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type NicheApproach = {
  __typename?: 'NicheApproach';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type NicheRelevantServices = {
  __typename?: 'NicheRelevantServices';
  id?: Maybe<Scalars['String']['output']>;
  angle?: Maybe<Scalars['String']['output']>;
};

export type NicheCaseStudiesMetrics = {
  __typename?: 'NicheCaseStudiesMetrics';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type NicheCaseStudies = {
  __typename?: 'NicheCaseStudies';
  title?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  metrics?: Maybe<Array<Maybe<NicheCaseStudiesMetrics>>>;
  summary?: Maybe<Scalars['String']['output']>;
};

export type NicheFaqs = {
  __typename?: 'NicheFaqs';
  q?: Maybe<Scalars['String']['output']>;
  a?: Maybe<Scalars['String']['output']>;
};

export type Niche = Node & Document & {
  __typename?: 'Niche';
  name: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  metaTitle: Scalars['String']['output'];
  metaDescription: Scalars['String']['output'];
  hero?: Maybe<NicheHero>;
  stats?: Maybe<Array<Maybe<NicheStats>>>;
  painPoints?: Maybe<Array<Maybe<NichePainPoints>>>;
  approach?: Maybe<Array<Maybe<NicheApproach>>>;
  relevantServices?: Maybe<Array<Maybe<NicheRelevantServices>>>;
  caseStudies?: Maybe<Array<Maybe<NicheCaseStudies>>>;
  faqs?: Maybe<Array<Maybe<NicheFaqs>>>;
  whatsappMessage?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NicheHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type NicheStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type NichePainPointsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type NicheApproachFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type NicheRelevantServicesFilter = {
  id?: InputMaybe<StringFilter>;
  angle?: InputMaybe<StringFilter>;
};

export type NicheCaseStudiesMetricsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type NicheCaseStudiesFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  metrics?: InputMaybe<NicheCaseStudiesMetricsFilter>;
  summary?: InputMaybe<StringFilter>;
};

export type NicheFaqsFilter = {
  q?: InputMaybe<StringFilter>;
  a?: InputMaybe<StringFilter>;
};

export type NicheFilter = {
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  metaTitle?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  hero?: InputMaybe<NicheHeroFilter>;
  stats?: InputMaybe<NicheStatsFilter>;
  painPoints?: InputMaybe<NichePainPointsFilter>;
  approach?: InputMaybe<NicheApproachFilter>;
  relevantServices?: InputMaybe<NicheRelevantServicesFilter>;
  caseStudies?: InputMaybe<NicheCaseStudiesFilter>;
  faqs?: InputMaybe<NicheFaqsFilter>;
  whatsappMessage?: InputMaybe<StringFilter>;
};

export type NicheConnectionEdges = {
  __typename?: 'NicheConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Niche>;
};

export type NicheConnection = Connection & {
  __typename?: 'NicheConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NicheConnectionEdges>>>;
};

export type ServiceHero = {
  __typename?: 'ServiceHero';
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
};

export type ServiceTiers = {
  __typename?: 'ServiceTiers';
  name?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  for?: Maybe<Scalars['String']['output']>;
};

export type Service = Node & Document & {
  __typename?: 'Service';
  name: Scalars['String']['output'];
  tagline: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  hero?: Maybe<ServiceHero>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tiers?: Maybe<Array<Maybe<ServiceTiers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiceHeroFilter = {
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
};

export type ServiceTiersFilter = {
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  for?: InputMaybe<StringFilter>;
};

export type ServiceFilter = {
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero?: InputMaybe<ServiceHeroFilter>;
  features?: InputMaybe<StringFilter>;
  tiers?: InputMaybe<ServiceTiersFilter>;
};

export type ServiceConnectionEdges = {
  __typename?: 'ServiceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Service>;
};

export type ServiceConnection = Connection & {
  __typename?: 'ServiceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiceConnectionEdges>>>;
};

export type Testimonial = Node & Document & {
  __typename?: 'Testimonial';
  clientName: Scalars['String']['output'];
  clientRole?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
  quote: Scalars['String']['output'];
  niche?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  rating?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type TestimonialFilter = {
  clientName?: InputMaybe<StringFilter>;
  clientRole?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
  quote?: InputMaybe<StringFilter>;
  niche?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type TestimonialConnectionEdges = {
  __typename?: 'TestimonialConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonial>;
};

export type TestimonialConnection = Connection & {
  __typename?: 'TestimonialConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBlog: Blog;
  createBlog: Blog;
  updateNiche: Niche;
  createNiche: Niche;
  updateService: Service;
  createService: Service;
  updateTestimonial: Testimonial;
  createTestimonial: Testimonial;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationCreateBlogArgs = {
  relativePath: Scalars['String']['input'];
  params: BlogMutation;
};


export type MutationUpdateNicheArgs = {
  relativePath: Scalars['String']['input'];
  params: NicheMutation;
};


export type MutationCreateNicheArgs = {
  relativePath: Scalars['String']['input'];
  params: NicheMutation;
};


export type MutationUpdateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationCreateServiceArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiceMutation;
};


export type MutationUpdateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};


export type MutationCreateTestimonialArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialMutation;
};

export type DocumentUpdateMutation = {
  blog?: InputMaybe<BlogMutation>;
  niche?: InputMaybe<NicheMutation>;
  service?: InputMaybe<ServiceMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  blog?: InputMaybe<BlogMutation>;
  niche?: InputMaybe<NicheMutation>;
  service?: InputMaybe<ServiceMutation>;
  testimonial?: InputMaybe<TestimonialMutation>;
};

export type BlogMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  cover?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  category?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NicheHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type NicheStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type NichePainPointsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type NicheApproachMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type NicheRelevantServicesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  angle?: InputMaybe<Scalars['String']['input']>;
};

export type NicheCaseStudiesMetricsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type NicheCaseStudiesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  metrics?: InputMaybe<Array<InputMaybe<NicheCaseStudiesMetricsMutation>>>;
  summary?: InputMaybe<Scalars['String']['input']>;
};

export type NicheFaqsMutation = {
  q?: InputMaybe<Scalars['String']['input']>;
  a?: InputMaybe<Scalars['String']['input']>;
};

export type NicheMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  metaTitle?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<NicheHeroMutation>;
  stats?: InputMaybe<Array<InputMaybe<NicheStatsMutation>>>;
  painPoints?: InputMaybe<Array<InputMaybe<NichePainPointsMutation>>>;
  approach?: InputMaybe<Array<InputMaybe<NicheApproachMutation>>>;
  relevantServices?: InputMaybe<Array<InputMaybe<NicheRelevantServicesMutation>>>;
  caseStudies?: InputMaybe<Array<InputMaybe<NicheCaseStudiesMutation>>>;
  faqs?: InputMaybe<Array<InputMaybe<NicheFaqsMutation>>>;
  whatsappMessage?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceTiersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  for?: InputMaybe<Scalars['String']['input']>;
};

export type ServiceMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero?: InputMaybe<ServiceHeroMutation>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tiers?: InputMaybe<Array<InputMaybe<ServiceTiersMutation>>>;
};

export type TestimonialMutation = {
  clientName?: InputMaybe<Scalars['String']['input']>;
  clientRole?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  niche?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  rating?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BlogPartsFragment = { __typename: 'Blog', title: string, excerpt: string, date: string, author: string, cover?: string | null, tags?: Array<string | null> | null, category?: string | null, featured?: boolean | null, body?: any | null };

export type NichePartsFragment = { __typename: 'Niche', name: string, icon: string, metaTitle: string, metaDescription: string, whatsappMessage?: string | null, hero?: { __typename: 'NicheHero', eyebrow?: string | null, title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, stats?: Array<{ __typename: 'NicheStats', value?: string | null, label?: string | null } | null> | null, painPoints?: Array<{ __typename: 'NichePainPoints', title?: string | null, description?: string | null } | null> | null, approach?: Array<{ __typename: 'NicheApproach', title?: string | null, description?: string | null } | null> | null, relevantServices?: Array<{ __typename: 'NicheRelevantServices', id?: string | null, angle?: string | null } | null> | null, caseStudies?: Array<{ __typename: 'NicheCaseStudies', title?: string | null, category?: string | null, duration?: string | null, services?: Array<string | null> | null, summary?: string | null, metrics?: Array<{ __typename: 'NicheCaseStudiesMetrics', label?: string | null, value?: string | null } | null> | null } | null> | null, faqs?: Array<{ __typename: 'NicheFaqs', q?: string | null, a?: string | null } | null> | null };

export type ServicePartsFragment = { __typename: 'Service', name: string, tagline: string, icon?: string | null, description?: string | null, features?: Array<string | null> | null, hero?: { __typename: 'ServiceHero', title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, tiers?: Array<{ __typename: 'ServiceTiers', name?: string | null, price?: string | null, for?: string | null } | null> | null };

export type TestimonialPartsFragment = { __typename: 'Testimonial', clientName: string, clientRole?: string | null, avatar?: string | null, quote: string, niche?: string | null, services?: Array<string | null> | null, rating?: number | null, featured?: boolean | null };

export type BlogQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BlogQuery = { __typename?: 'Query', blog: { __typename: 'Blog', id: string, title: string, excerpt: string, date: string, author: string, cover?: string | null, tags?: Array<string | null> | null, category?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BlogConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BlogFilter>;
}>;


export type BlogConnectionQuery = { __typename?: 'Query', blogConnection: { __typename?: 'BlogConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BlogConnectionEdges', cursor: string, node?: { __typename: 'Blog', id: string, title: string, excerpt: string, date: string, author: string, cover?: string | null, tags?: Array<string | null> | null, category?: string | null, featured?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NicheQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NicheQuery = { __typename?: 'Query', niche: { __typename: 'Niche', id: string, name: string, icon: string, metaTitle: string, metaDescription: string, whatsappMessage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'NicheHero', eyebrow?: string | null, title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, stats?: Array<{ __typename: 'NicheStats', value?: string | null, label?: string | null } | null> | null, painPoints?: Array<{ __typename: 'NichePainPoints', title?: string | null, description?: string | null } | null> | null, approach?: Array<{ __typename: 'NicheApproach', title?: string | null, description?: string | null } | null> | null, relevantServices?: Array<{ __typename: 'NicheRelevantServices', id?: string | null, angle?: string | null } | null> | null, caseStudies?: Array<{ __typename: 'NicheCaseStudies', title?: string | null, category?: string | null, duration?: string | null, services?: Array<string | null> | null, summary?: string | null, metrics?: Array<{ __typename: 'NicheCaseStudiesMetrics', label?: string | null, value?: string | null } | null> | null } | null> | null, faqs?: Array<{ __typename: 'NicheFaqs', q?: string | null, a?: string | null } | null> | null } };

export type NicheConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NicheFilter>;
}>;


export type NicheConnectionQuery = { __typename?: 'Query', nicheConnection: { __typename?: 'NicheConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NicheConnectionEdges', cursor: string, node?: { __typename: 'Niche', id: string, name: string, icon: string, metaTitle: string, metaDescription: string, whatsappMessage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'NicheHero', eyebrow?: string | null, title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, stats?: Array<{ __typename: 'NicheStats', value?: string | null, label?: string | null } | null> | null, painPoints?: Array<{ __typename: 'NichePainPoints', title?: string | null, description?: string | null } | null> | null, approach?: Array<{ __typename: 'NicheApproach', title?: string | null, description?: string | null } | null> | null, relevantServices?: Array<{ __typename: 'NicheRelevantServices', id?: string | null, angle?: string | null } | null> | null, caseStudies?: Array<{ __typename: 'NicheCaseStudies', title?: string | null, category?: string | null, duration?: string | null, services?: Array<string | null> | null, summary?: string | null, metrics?: Array<{ __typename: 'NicheCaseStudiesMetrics', label?: string | null, value?: string | null } | null> | null } | null> | null, faqs?: Array<{ __typename: 'NicheFaqs', q?: string | null, a?: string | null } | null> | null } | null } | null> | null } };

export type ServiceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiceQuery = { __typename?: 'Query', service: { __typename: 'Service', id: string, name: string, tagline: string, icon?: string | null, description?: string | null, features?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServiceHero', title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, tiers?: Array<{ __typename: 'ServiceTiers', name?: string | null, price?: string | null, for?: string | null } | null> | null } };

export type ServiceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiceFilter>;
}>;


export type ServiceConnectionQuery = { __typename?: 'Query', serviceConnection: { __typename?: 'ServiceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiceConnectionEdges', cursor: string, node?: { __typename: 'Service', id: string, name: string, tagline: string, icon?: string | null, description?: string | null, features?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'ServiceHero', title?: string | null, titleHighlight?: string | null, subtitle?: string | null } | null, tiers?: Array<{ __typename: 'ServiceTiers', name?: string | null, price?: string | null, for?: string | null } | null> | null } | null } | null> | null } };

export type TestimonialQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialQuery = { __typename?: 'Query', testimonial: { __typename: 'Testimonial', id: string, clientName: string, clientRole?: string | null, avatar?: string | null, quote: string, niche?: string | null, services?: Array<string | null> | null, rating?: number | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialFilter>;
}>;


export type TestimonialConnectionQuery = { __typename?: 'Query', testimonialConnection: { __typename?: 'TestimonialConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialConnectionEdges', cursor: string, node?: { __typename: 'Testimonial', id: string, clientName: string, clientRole?: string | null, avatar?: string | null, quote: string, niche?: string | null, services?: Array<string | null> | null, rating?: number | null, featured?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BlogPartsFragmentDoc = gql`
    fragment BlogParts on Blog {
  __typename
  title
  excerpt
  date
  author
  cover
  tags
  category
  featured
  body
}
    `;
export const NichePartsFragmentDoc = gql`
    fragment NicheParts on Niche {
  __typename
  name
  icon
  metaTitle
  metaDescription
  hero {
    __typename
    eyebrow
    title
    titleHighlight
    subtitle
  }
  stats {
    __typename
    value
    label
  }
  painPoints {
    __typename
    title
    description
  }
  approach {
    __typename
    title
    description
  }
  relevantServices {
    __typename
    id
    angle
  }
  caseStudies {
    __typename
    title
    category
    duration
    services
    metrics {
      __typename
      label
      value
    }
    summary
  }
  faqs {
    __typename
    q
    a
  }
  whatsappMessage
}
    `;
export const ServicePartsFragmentDoc = gql`
    fragment ServiceParts on Service {
  __typename
  name
  tagline
  icon
  description
  hero {
    __typename
    title
    titleHighlight
    subtitle
  }
  features
  tiers {
    __typename
    name
    price
    for
  }
}
    `;
export const TestimonialPartsFragmentDoc = gql`
    fragment TestimonialParts on Testimonial {
  __typename
  clientName
  clientRole
  avatar
  quote
  niche
  services
  rating
  featured
}
    `;
export const BlogDocument = gql`
    query blog($relativePath: String!) {
  blog(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BlogParts
  }
}
    ${BlogPartsFragmentDoc}`;
export const BlogConnectionDocument = gql`
    query blogConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BlogFilter) {
  blogConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BlogParts
      }
    }
  }
}
    ${BlogPartsFragmentDoc}`;
export const NicheDocument = gql`
    query niche($relativePath: String!) {
  niche(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NicheParts
  }
}
    ${NichePartsFragmentDoc}`;
export const NicheConnectionDocument = gql`
    query nicheConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NicheFilter) {
  nicheConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NicheParts
      }
    }
  }
}
    ${NichePartsFragmentDoc}`;
export const ServiceDocument = gql`
    query service($relativePath: String!) {
  service(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiceParts
  }
}
    ${ServicePartsFragmentDoc}`;
export const ServiceConnectionDocument = gql`
    query serviceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiceFilter) {
  serviceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiceParts
      }
    }
  }
}
    ${ServicePartsFragmentDoc}`;
export const TestimonialDocument = gql`
    query testimonial($relativePath: String!) {
  testimonial(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialParts
  }
}
    ${TestimonialPartsFragmentDoc}`;
export const TestimonialConnectionDocument = gql`
    query testimonialConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialFilter) {
  testimonialConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialParts
      }
    }
  }
}
    ${TestimonialPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      blog(variables: BlogQueryVariables, options?: C): Promise<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}> {
        return requester<{data: BlogQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogQueryVariables, query: string}, BlogQueryVariables>(BlogDocument, variables, options);
      },
    blogConnection(variables?: BlogConnectionQueryVariables, options?: C): Promise<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}> {
        return requester<{data: BlogConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BlogConnectionQueryVariables, query: string}, BlogConnectionQueryVariables>(BlogConnectionDocument, variables, options);
      },
    niche(variables: NicheQueryVariables, options?: C): Promise<{data: NicheQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NicheQueryVariables, query: string}> {
        return requester<{data: NicheQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NicheQueryVariables, query: string}, NicheQueryVariables>(NicheDocument, variables, options);
      },
    nicheConnection(variables?: NicheConnectionQueryVariables, options?: C): Promise<{data: NicheConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NicheConnectionQueryVariables, query: string}> {
        return requester<{data: NicheConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NicheConnectionQueryVariables, query: string}, NicheConnectionQueryVariables>(NicheConnectionDocument, variables, options);
      },
    service(variables: ServiceQueryVariables, options?: C): Promise<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}> {
        return requester<{data: ServiceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceQueryVariables, query: string}, ServiceQueryVariables>(ServiceDocument, variables, options);
      },
    serviceConnection(variables?: ServiceConnectionQueryVariables, options?: C): Promise<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}> {
        return requester<{data: ServiceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiceConnectionQueryVariables, query: string}, ServiceConnectionQueryVariables>(ServiceConnectionDocument, variables, options);
      },
    testimonial(variables: TestimonialQueryVariables, options?: C): Promise<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}> {
        return requester<{data: TestimonialQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialQueryVariables, query: string}, TestimonialQueryVariables>(TestimonialDocument, variables, options);
      },
    testimonialConnection(variables?: TestimonialConnectionQueryVariables, options?: C): Promise<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialConnectionQueryVariables, query: string}, TestimonialConnectionQueryVariables>(TestimonialConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4002/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  