// One-off generator: reads the workflow result JSON and emits
//   src/lib/catalog.ts, src/lib/proof.ts, supabase/seed.sql
// Usage: node scripts/gen-content.mjs <path-to-result.json>
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const inPath = process.argv[2];
if (!inPath) {
  console.error("Pass the result JSON file path as arg 1");
  process.exit(1);
}

let raw = readFileSync(inPath, "utf8").trim();
// In case the file has any leading/trailing non-JSON noise, slice to outer braces.
const first = raw.indexOf("{");
const last = raw.lastIndexOf("}");
if (first > 0 || last < raw.length - 1) raw = raw.slice(first, last + 1);
const parsed = JSON.parse(raw);
// Workflow output is wrapped: { summary, agentCount, logs, result: {...} }
const result = parsed.result ?? parsed;

const decodeEntities = (s) =>
  typeof s === "string"
    ? s
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#0?39;/g, "'")
        .replace(/&apos;/g, "'")
        .replace(/&nbsp;/g, " ")
    : s;

const deep = (v) => {
  if (typeof v === "string") return decodeEntities(v);
  if (Array.isArray(v)) return v.map(deep);
  if (v && typeof v === "object") {
    const o = {};
    for (const k of Object.keys(v)) o[k] = deep(v[k]);
    return o;
  }
  return v;
};

const clean = deep(result);

// ─── catalog.ts ───
const contentBySlug = {};
for (const s of clean.services) contentBySlug[s.slug] = s.data;

const catalogTs = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
import type { ServiceContent } from "./types";
import { SERVICE_META } from "./constants";

type ServiceBody = Omit<
  ServiceContent,
  "slug" | "name" | "icon" | "accent" | "short"
>;

const CONTENT: Record<string, ServiceBody> = ${JSON.stringify(contentBySlug, null, 2)};

export const SERVICES: ServiceContent[] = SERVICE_META.map((m) => ({
  ...m,
  ...CONTENT[m.slug],
}));

export function getService(slug: string): ServiceContent | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export function serviceSlugs(): string[] {
  return SERVICE_META.map((m) => m.slug);
}
`;
writeFileSync(resolve(root, "src/lib/catalog.ts"), catalogTs);

// ─── proof.ts ───
const proofTs = `// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
import type { Testimonial, SocialProofEvent } from "./types";

export const TESTIMONIALS: Testimonial[] = ${JSON.stringify(clean.proof.testimonials, null, 2)};

export const SOCIAL_PROOF: SocialProofEvent[] = ${JSON.stringify(clean.proof.social_proof, null, 2)};
`;
writeFileSync(resolve(root, "src/lib/proof.ts"), proofTs);

// ─── seed.sql (aged_domains) ───
const domains = clean.domains.domains;
const esc = (s) => String(s).replace(/'/g, "''");
const cols = [
  "domain", "tld", "da", "pa", "dr", "ur", "tf", "cf",
  "age_years", "referring_domains", "backlinks", "spam_score",
  "niche", "language", "price_idr", "status", "highlight",
];
const values = domains
  .map((d) => {
    const row = [
      `'${esc(d.domain)}'`,
      `'${esc(d.tld)}'`,
      d.da, d.pa, d.dr, d.ur, d.tf, d.cf,
      d.age_years, d.referring_domains, d.backlinks, d.spam_score,
      `'${esc(d.niche)}'`,
      `'${esc(d.language)}'`,
      d.price_idr,
      `'${esc(d.status)}'`,
      `'${esc(d.highlight)}'`,
    ];
    return `  (${row.join(", ")})`;
  })
  .join(",\n");

const seedSql = `-- AUTO-GENERATED by scripts/gen-content.mjs — aged_domains seed data.
-- Safe to re-run: clears existing seed rows by domain before inserting.
delete from public.hitam_aged_domains
where domain in (${domains.map((d) => `'${esc(d.domain)}'`).join(", ")});

insert into public.hitam_aged_domains
  (${cols.join(", ")})
values
${values};
`;
mkdirSync(resolve(root, "supabase"), { recursive: true });
writeFileSync(resolve(root, "supabase/seed.sql"), seedSql);

console.log(
  `OK — ${clean.services.length} services, ${domains.length} domains, ` +
    `${clean.proof.testimonials.length} testimonials, ${clean.proof.social_proof.length} social-proof events.`,
);
