// Parse the raw domain lists into seed.sql (aged_domains + backlink_sites).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => {
  try {
    return readFileSync(resolve(root, "scripts/data", p), "utf8");
  } catch {
    return "";
  }
};
const lines = (txt) =>
  txt.split("\n").map((l) => l.trim()).filter((l) => l && !l.startsWith("#"));
const esc = (s) => String(s).replace(/'/g, "''");
const cleanDomain = (d) => d.toLowerCase().replace(/^https?:\/\//, "").replace(/\/$/, "").replace(/\.$/, "");
const num = (t) => Number(String(t).replace(/[^\d.]/g, "")) || 0;

const TAGMAP = {
  "HIGH INDEX": "index tinggi",
  INDEXED: "ter-index Google",
  subpages: "banyak subpage ke-index",
  "DOMAIN INDO": "domain Indonesia",
  "SUPER HIGH TRAFFIC": "traffic super tinggi",
  "HIGH TRAFFIC": "traffic tinggi",
  TRAFFIC: "ada traffic",
  "FULL WIKI": "backlink Wikipedia",
};

// ───────── Aged domains ─────────
function parseAged(txt, tier) {
  return lines(txt).map((line) => {
    const tokens = line.split(/\s+/);
    const domain = cleanDomain(tokens[0]);
    const tld = domain.split(".").slice(1).join(".") || "com";

    const ageM = line.match(/(\d+)\s*Years?/i);
    const age_years = ageM ? Number(ageM[1]) : 0;
    const preAge = ageM ? line.slice(0, ageM.index) : line.split(/Rp/i)[0];
    const nums = preAge
      .split(/\s+/)
      .slice(1)
      .filter((t) => /^\d+(\.\d+)?$/.test(t))
      .map(Number);
    const [dr = 0, da = 0, pa = 0, ss = 0] = nums;

    const priceM = line.match(/Rp\s?([\d.]+)/);
    const price_idr = priceM ? Number(priceM[1].replace(/\D/g, "")) || 0 : 0;

    const statusRaw = (line.match(/\b(Ready|Booked|Sold)\b/i) || [])[1] || "Ready";
    const status =
      /booked/i.test(statusRaw) ? "reserved" : /sold/i.test(statusRaw) ? "sold" : "available";

    const tags = [...line.matchAll(/\[([^\]]+)\]/g)].map((m) => m[1].trim());
    const tr = tags.map((t) => TAGMAP[t.toUpperCase()] || TAGMAP[t] || null).filter(Boolean);
    const highlight =
      `Aged ${age_years || "?"} tahun` + (tr.length ? ` · ${[...new Set(tr)].join(", ")}` : "");

    return {
      domain, tld,
      da, pa, dr: Math.round(dr), ur: 0, tf: 0, cf: 0,
      age_years, referring_domains: 0, backlinks: 0, spam_score: Math.round(ss),
      niche: "general", language: "en", price_idr, status, highlight, tier,
    };
  });
}

const agedRaw = [
  ...parseAged(read("aged-regular.txt"), "regular"),
  ...parseAged(read("aged-premium.txt"), "premium"),
  ...parseAged(read("aged-diamond.txt"), "diamond"),
];
const agedSeen = new Set();
const aged = agedRaw.filter((d) => {
  if (!d.domain || agedSeen.has(d.domain)) return false;
  agedSeen.add(d.domain);
  return true;
});

// ───────── Backlink sites ─────────
function parseBacklinkEdu(txt) {
  return lines(txt).map((line) => {
    const t = line.split(/\s+/);
    const domain = cleanDomain(t[0]);
    return {
      domain,
      da: num(t[1]), pa: num(t[2]), dr: Math.round(num(t[3])), ss: num(t[4]),
      backlinks: t[5] || null,
      kind: /\.(ac|co)\.id$/.test(domain) ? "edu" : "general",
    };
  });
}
function parseBacklinkJournal(txt) {
  return lines(txt).map((line) => {
    const t = line.split(/\s+/);
    const domain = cleanDomain(t[0]);
    return {
      domain,
      da: num(t[1]), pa: num(t[2]), dr: 0, ss: num(t[3]),
      backlinks: null, kind: "journal",
    };
  });
}
const backlinkRaw = [...parseBacklinkEdu(read("backlink-edu.txt")), ...parseBacklinkJournal(read("backlink-journal.txt"))];
const blSeen = new Set();
const backlinks = backlinkRaw.filter((d) => {
  if (!d.domain || blSeen.has(d.domain)) return false;
  blSeen.add(d.domain);
  return true;
});

// ───────── Emit seed.sql ─────────
const agedCols =
  "domain, tld, da, pa, dr, ur, tf, cf, age_years, referring_domains, backlinks, spam_score, niche, language, price_idr, status, highlight, tier";
const agedValues = aged
  .map((d) =>
    `  ('${esc(d.domain)}','${esc(d.tld)}',${d.da},${d.pa},${d.dr},${d.ur},${d.tf},${d.cf},${d.age_years},${d.referring_domains},${d.backlinks},${d.spam_score},'${esc(d.niche)}','${esc(d.language)}',${d.price_idr},'${esc(d.status)}','${esc(d.highlight)}','${esc(d.tier)}')`,
  )
  .join(",\n");

const blCols = "domain, da, pa, dr, ss, backlinks, kind";
const blValues = backlinks
  .map((d) =>
    `  ('${esc(d.domain)}',${d.da},${d.pa},${d.dr},${d.ss},${d.backlinks ? `'${esc(d.backlinks)}'` : "null"},'${esc(d.kind)}')`,
  )
  .join(",\n");

const sql = `-- AUTO-GENERATED by scripts/parse-domains.mjs
-- Aged domains: ${aged.length} unique. Backlink sites: ${backlinks.length} unique.

delete from public.hitam_aged_domains;
insert into public.hitam_aged_domains (${agedCols})
values
${agedValues};

delete from public.hitam_backlink_sites;
insert into public.hitam_backlink_sites (${blCols})
values
${blValues};
`;

writeFileSync(resolve(root, "supabase/seed.sql"), sql);
console.log(
  `OK — aged: ${aged.length} (regular/premium/diamond), backlink: ${backlinks.length}. ` +
    `(raw aged ${agedRaw.length}, raw backlink ${backlinkRaw.length})`,
);
