// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
import type { ServiceContent } from "./types";
import { SERVICE_META } from "./constants";

type ServiceBody = Omit<
  ServiceContent,
  "slug" | "name" | "icon" | "accent" | "short"
>;

const CONTENT: Record<string, ServiceBody> = {
  "hunting-aged-domain": {
    "tagline": "Aged domain custom, di-hunt sesuai brief kamu — bukan stok sisa, bukan metrik bohongan.",
    "heroBadge": "🔒 Clean History Guaranteed",
    "heroTitle": "Domain tua bersih,",
    "heroTitleHighlight": "di-hunt khusus buat money site kamu.",
    "heroSubtitle": "Kasih kami brief: niche, target DA/DR, bahasa, dan history yang kamu mau. Kami hunting kandidatnya satu per satu, audit habis-habisan history dan backlink-nya, verifikasi metrik real lewat Ahrefs + Moz + Majestic, lalu hand-over domain bersih siap pakai. Bukan domain random dari stok marketplace — ini hunting on-demand, dikurasi khusus buat target ranking kamu.",
    "intro": [
      "Authority itu butuh waktu bertahun-tahun. Aged domain memotong jalannya. Tapi 90% domain tua yang beredar di luar sana itu jebakan: history judi/dewasa yang nyangkut, backlink toxic, metrik DR yang di-pump pakai PBN murahan, atau status deindex yang gak ketahuan sampai kamu udah bayar. Beli yang salah, bukannya naik ranking, money site kamu malah kena seret turun.",
      "Di sinilah hunting on-demand beda dari beli stok. Kami gak nawarin kamu daftar domain sisa yang udah dipegang 50 orang lain. Kami berangkat dari brief kamu — niche apa, target DA/DR berapa, bahasa apa, history sebersih apa — lalu berburu kandidat yang benar-benar cocok. Setiap kandidat lewat audit history (Wayback Machine, dropped record, status index), audit spam & toxic backlink, dan verifikasi silang metrik di tiga tools sekaligus biar gak ketipu angka inflated.",
      "Yang kamu terima di akhir: domain bersih, metrik real yang bisa kamu cek ulang sendiri, plus dokumentasi audit lengkap. Dan kalau metrik utama drop signifikan dalam masa garansi, kami replace. Ini cara aman main aged domain tanpa harus jadi korban penjual yang cuma jualan angka."
    ],
    "features": [
      "Hunting 100% custom sesuai brief — niche, DA/DR, bahasa, history kamu yang nentuin",
      "Verifikasi metrik silang 3 tools: Ahrefs (DR), Moz (DA), Majestic (TF/CF)",
      "Audit history penuh via Wayback Machine — cek bekas judi, dewasa, gambling, scam",
      "Deteksi metrik inflated & PBN-pumped sebelum kamu bayar",
      "Audit toxic & spam backlink, plus disavow-ready list",
      "Cek status index Google & riwayat dropped/deindex domain",
      "Trust Flow / Citation Flow ratio sehat (bukan link farm)",
      "Garansi replace kalau metrik utama drop dalam masa garansi",
      "Hand-over lengkap: domain + laporan audit + raw data metrik",
      "Domain eksklusif buat kamu — gak dijual ke klien lain"
    ],
    "packages": [
      {
        "name": "Solo Hunt",
        "priceLabel": "Mulai Rp 1,5jt",
        "for": "1 domain target sesuai brief, niche umum, DA/DR menengah — buat tes air atau single money site",
        "includes": [
          "1 aged domain sesuai brief kamu",
          "Target DA/DR menengah (DR 15-30)",
          "Audit history dasar (Wayback + status index)",
          "Verifikasi metrik via Ahrefs",
          "Cek spam score & toxic backlink ringkas",
          "Laporan audit ringkas (PDF)",
          "Garansi replace 14 hari kalau metrik drop"
        ],
        "popular": false
      },
      {
        "name": "Pro Hunt",
        "priceLabel": "Mulai Rp 4,5jt",
        "for": "Paket 3 domain dikurasi, niche spesifik, target DA/DR tinggi & clean history ketat — buat scaling PBN atau cluster money site",
        "includes": [
          "3 aged domain dikurasi sesuai brief",
          "Target DA/DR tinggi (DR 30-50)",
          "Niche & bahasa spesifik sesuai pesanan",
          "Audit history penuh (Wayback + dropped record + deindex check)",
          "Verifikasi silang 3 tools (Ahrefs + Moz + Majestic)",
          "Audit toxic backlink + disavow-ready list",
          "Laporan audit lengkap + raw data metrik per domain",
          "Garansi replace 30 hari",
          "Prioritas pengerjaan"
        ],
        "popular": true
      },
      {
        "name": "Authority Hunt",
        "priceLabel": "Rp 12jt+",
        "for": "High-DR / niche super sulit / volume besar, history super bersih & metrik premium — buat agency, reseller, atau brand-grade money site",
        "includes": [
          "High-DR domain (DR 50+) atau niche super sulit",
          "Volume custom (5, 10, 20+ domain)",
          "History audit forensik (full timeline + manual review)",
          "Verifikasi silang 3 tools + manual spot-check backlink",
          "Link profile & anchor text analysis mendalam + topical/geo match",
          "Laporan forensik lengkap per domain + rekomendasi penggunaan",
          "Garansi replace 60 hari",
          "Dedicated handler + konsultasi strategi deployment",
          "Reseller / white-label rate tersedia"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Laporan Audit Per Domain",
        "items": [
          "Timeline history lengkap dari Wayback Machine (screenshot bukti tiap era)",
          "Verifikasi clean history — bebas konten judi, dewasa, gambling, scam, spam",
          "Status index Google terkini + riwayat dropped/deindex",
          "Spam score & toxic backlink ratio dengan flag merah yang jelas",
          "Verdict: aman dipakai, perlu disavow, atau di-skip"
        ]
      },
      {
        "title": "Verifikasi Metrik Real (Anti-Inflated)",
        "items": [
          "DR (Ahrefs) + screenshot dashboard sebagai bukti",
          "DA & PA (Moz) cross-check",
          "Trust Flow & Citation Flow (Majestic) + TF/CF ratio sehat",
          "Referring domains real vs link farm — dibedakan jelas",
          "Catatan deteksi PBN-pumped atau metrik artifisial kalau ada"
        ]
      },
      {
        "title": "Backlink & Link Profile",
        "items": [
          "Daftar referring domains beserta kualitasnya",
          "Anchor text distribution (cek over-optimization)",
          "Toxic & spam link yang di-flag + disavow-ready list (.txt)",
          "Topical relevance backlink terhadap niche target kamu",
          "Geo-distribution backlink (relevan untuk geo-targeting)"
        ]
      },
      {
        "title": "Hand-Over & Ownership",
        "items": [
          "Domain di-reclaim/registrasi atas nama kamu — ownership penuh",
          "Panduan transfer/push ke registrar pilihan kamu",
          "Raw data metrik (export) biar kamu bisa cek ulang sendiri",
          "Rekomendasi penggunaan: money site, PBN tier, atau 301 redirect",
          "Sertifikat garansi replace dengan periode sesuai paket"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Brief & Scoping",
        "desc": "Kamu kasih detail: niche, target DA/DR, bahasa, level clean history, dan rencana pakai (money site / PBN / 301). Kami kunci kriteria dan budget, lalu mulai berburu. Makin spesifik brief kamu, makin presisi kandidatnya.",
        "duration": "Hari 1"
      },
      {
        "step": "02",
        "title": "Riset & Sourcing Kandidat",
        "desc": "Kami sisir pasar dropped domain, auction, dan expired sesuai kriteria. Long-list kandidat dikumpulkan dan disaring kasar berdasarkan metrik awal dan relevansi niche sebelum masuk audit mendalam.",
        "duration": "Hari 2-4"
      },
      {
        "step": "03",
        "title": "Audit History & Verifikasi Metrik",
        "desc": "Tiap kandidat lewat audit forensik: Wayback Machine, status index, dropped record, spam score, toxic backlink, dan verifikasi silang metrik di Ahrefs + Moz + Majestic. Yang inflated atau ada history kotor langsung dicoret.",
        "duration": "Hari 4-8"
      },
      {
        "step": "04",
        "title": "Reclaim / Registrasi",
        "desc": "Kandidat lolos audit kami amankan — reclaim dari auction atau registrasi langsung — sebelum keburu disambar orang lain. Kepemilikan disiapkan untuk pindah ke nama kamu.",
        "duration": "Hari 8-10"
      },
      {
        "step": "05",
        "title": "Hand-Over Lengkap",
        "desc": "Domain + laporan audit + raw data metrik + disavow list diserahkan. Kami pandu transfer ke registrar kamu dan kasih rekomendasi deployment. Garansi replace mulai berlaku sejak hand-over.",
        "duration": "Hari 10-12"
      }
    ],
    "stats": [
      {
        "value": "3 tools",
        "label": "Verifikasi metrik silang (Ahrefs + Moz + Majestic)"
      },
      {
        "value": "100%",
        "label": "Domain di-audit history-nya, bukan asal metrik"
      },
      {
        "value": "60 hari",
        "label": "Garansi replace maksimal (paket Authority)"
      },
      {
        "value": "0 inflated",
        "label": "Metrik PBN-pumped ditolak sebelum hand-over"
      }
    ],
    "faqs": [
      {
        "q": "Bedanya hunting on-demand sama beli di Marketplace aged domain apa?",
        "a": "Marketplace itu stok siap beli — kamu pilih dari domain yang sudah ada, bisa jadi udah dilirik banyak orang. Hunting on-demand kebalikannya: kami berburu dari nol sesuai brief spesifik kamu (niche, DA/DR, bahasa, history). Hasilnya eksklusif, dikurasi khusus, dan gak dijual ke klien lain. Kalau kebutuhan kamu generik dan butuh cepat, marketplace cukup. Kalau kamu butuh domain yang benar-benar pas dengan target ranking, hunting jawabannya."
      },
      {
        "q": "Gimana kalian mastiin metriknya real, bukan DR yang di-pump?",
        "a": "Kami gak percaya satu angka dari satu tool. Tiap domain diverifikasi silang di Ahrefs (DR), Moz (DA), dan Majestic (TF/CF). Kalau DR tinggi tapi referring domain-nya cuma link farm atau Trust Flow-nya anjlok, itu sinyal metrik dipompa pakai PBN murahan — langsung kami coret. Kamu juga dapat raw data screenshot buat cek ulang sendiri. Kami gak akan hand-over domain yang metriknya artifisial."
      },
      {
        "q": "Apa garansinya kalau setelah dibeli metriknya drop?",
        "a": "Kami kasih garansi replace: kalau metrik utama (DR/DA) drop signifikan dalam masa garansi — 14 hari (Solo), 30 hari (Pro), atau 60 hari (Authority) — kami ganti dengan domain setara sesuai brief, gratis. Yang gak ditanggung: drop karena kamu sendiri yang spam backlink berlebihan atau deploy konten yang melanggar guideline setelah hand-over. Garansi soal kualitas domain saat diserahkan, bukan cara kamu pakai."
      },
      {
        "q": "History 'bersih' itu maksudnya gimana? Pasti aman?",
        "a": "Clean history artinya kami audit penuh via Wayback Machine dan record dropped: bebas bekas konten judi, dewasa, gambling, scam, atau spam yang bisa nyeret reputasi domain. Kami juga cek status index dan toxic backlink. Tapi jujur: 'bersih saat audit' bukan jaminan absolut Google gak akan pernah re-evaluasi history lama. Kami minimalkan risiko serendah mungkin dengan audit forensik — itu yang bisa kami kontrol, dan itu yang kami garansi."
      },
      {
        "q": "Domainnya jadi atas nama siapa? Aman gak soal kerahasiaan?",
        "a": "Domain di-reclaim atau registrasi lalu di-hand-over jadi milik kamu sepenuhnya — kami pandu push/transfer ke registrar pilihan kamu. Soal kerahasiaan: brief, niche, dan domain yang kamu pesan kami jaga konfidensial dan gak kami pajang sebagai portfolio. Apa yang kamu lakukan dengan domainnya setelah hand-over sepenuhnya urusan dan tanggung jawab kamu."
      },
      {
        "q": "Berapa lama prosesnya dari brief sampai terima domain?",
        "a": "Solo Hunt biasanya 5-7 hari kerja. Pro Hunt 7-12 hari kerja tergantung kerumitan brief. Authority Hunt 12-20 hari kerja, karena high-DR atau niche super sulit butuh sourcing lebih dalam dan audit forensik manual. Niche yang sangat sempit atau target DA/DR tinggi bisa nambah waktu — kami kasih estimasi realistis di tahap scoping, bukan janji palsu."
      },
      {
        "q": "Sistem pembayarannya gimana?",
        "a": "Umumnya 50% DP di awal buat mulai hunting, 50% pelunasan saat domain lolos audit dan siap hand-over. Untuk paket Authority atau volume besar, bisa diatur per-batch. Kami terima transfer bank dan crypto (USDT) buat klien yang prefer. Detail dikonfirmasi via WhatsApp di tahap scoping."
      },
      {
        "q": "Aged domain ini cocok buat brand jangka panjang gak?",
        "a": "Tergantung gimana kamu pakai. Untuk money site, PBN, niche site, atau 301 redirect buat dongkrak authority — ini powerful banget. Untuk brand korporat jangka panjang yang gak mau ambil risiko sama sekali, kami jujur: aged domain selalu bawa residual risk dari history-nya. Kalau kamu butuh sebersih-bersihnya tanpa kompromi, mending diskusi dulu sama kami soal trade-off-nya sebelum mutusin."
      }
    ],
    "riskNote": "Aged domain adalah strategi high-risk high-reward: history lama selalu menyisakan residual risk yang bisa di-re-evaluasi Google kapan saja, sehingga lebih cocok untuk money site, PBN, dan churn-and-burn ketimbang brand korporat jangka panjang. Kami meminimalkan risiko lewat audit forensik dan menggaransi kualitas domain saat hand-over — tapi keputusan dan cara penggunaan setelah serah-terima sepenuhnya tanggung jawab kamu."
  },
  "black-hat-seo": {
    "tagline": "Ranking kilat halaman 1 Google. Berani ambil risiko, panen hasilnya duluan.",
    "heroBadge": "⚡ Ranking Kilat 7-30 Hari",
    "heroTitle": "Halaman 1 Google secepat mungkin,",
    "heroTitleHighlight": "tanpa nunggu 6 bulan.",
    "heroSubtitle": "White-hat butuh waktu. Kamu butuh hasil sekarang. Divisi Hitam Para Suhu Digital main agresif: PBN network, parasite SEO, mass indexing, dan link velocity tinggi buat dorong keyword kamu ke halaman 1 dalam hitungan minggu. High-risk, high-reward, dan kami jujur soal dua-duanya.",
    "intro": [
      "Agency biasa nolak niche kamu? Industri kamu dianggap \"terlalu abu-abu\", kompetisinya brutal, atau kamu cuma gak punya waktu nunggu SEO konvensional matang dalam 6-12 bulan? Di sinilah divisi Hitam main. Kami terima berbagai industri — termasuk yang ditolak agency mainstream — dan kami fokus ke satu hal: bikin keyword kamu nangkring di halaman 1 Google secepat yang teknik agresif memungkinkan.",
      "Pendekatan kami bukan tebak-tebakan. Kami bangun dan kontrol jaringan PBN (Private Blog Network) dengan metrik otoritas terjaga, manfaatin parasite SEO di platform high-authority, dan jalanin mass indexing biar setiap aset link kebaca cepat sama Google. Link velocity diatur strategis supaya momentum ranking kebentuk dalam minggu pertama, bukan kuartal pertama.",
      "Tapi kami main lurus soal ekspektasi: black-hat itu high-risk high-reward. Cocok banget buat money site, affiliate, lead-gen agresif, dan strategi churn-and-burn. Kalau yang kamu kejar adalah ranking kilat dan ROI cepat dengan mata terbuka soal risikonya, kamu ada di tempat yang tepat. Kami kasih opsi churn-and-burn buat hasil instan, atau pendekatan longterm yang lebih hati-hati buat aset yang mau kamu jaga lebih lama."
    ],
    "features": [
      "Ranking halaman 1 dalam 7-30 hari (tergantung kompetisi keyword)",
      "PBN network premium dengan DA/DR terjaga & footprint bersih",
      "Parasite SEO di platform high-authority (ranking numpang otoritas besar)",
      "Mass indexing — setiap backlink kebaca Google dalam hitungan jam",
      "Link velocity tinggi yang diatur strategis biar momentum maksimal",
      "Niche edit & contextual link placement di artikel relevan",
      "Terima berbagai industri, termasuk niche yang ditolak agency biasa",
      "Pilihan strategi: churn-and-burn (instan) vs longterm (lebih awet)",
      "Monitoring ranking harian + alert kalau ada fluktuasi",
      "Anonimitas terjaga — footprint dan jejak digital diminimalisir"
    ],
    "packages": [
      {
        "name": "Starter Burn",
        "priceLabel": "Mulai Rp 4,5jt/bulan",
        "for": "Money site / churn-and-burn, 5-10 keyword low-medium competition",
        "includes": [
          "5-10 target keyword",
          "PBN links dari jaringan tier-1",
          "Mass indexing semua backlink",
          "Niche edit kontekstual",
          "Target ranking 14-30 hari",
          "Monitoring ranking mingguan",
          "Laporan posisi keyword bulanan"
        ],
        "popular": false
      },
      {
        "name": "Pro Velocity",
        "priceLabel": "Mulai Rp 12jt/bulan",
        "for": "Lead-gen & affiliate serius, 15-30 keyword medium-high competition",
        "includes": [
          "15-30 target keyword",
          "PBN multi-tier + parasite SEO",
          "Link velocity tinggi terkontrol",
          "Mass indexing prioritas",
          "Niche edit + contextual links premium",
          "Target ranking 7-21 hari",
          "Monitoring ranking harian + alert",
          "Laporan mingguan + sesi strategi",
          "Pilihan churn-and-burn atau longterm"
        ],
        "popular": true
      },
      {
        "name": "Brutal Dominate",
        "priceLabel": "Rp 30jt+/bulan",
        "for": "Niche super kompetitif / multi-money-site, 50+ keyword agresif",
        "includes": [
          "50+ target keyword lintas domain",
          "Full PBN network dedicated + parasite stacking",
          "Link velocity maksimal + anchor diversity",
          "Mass indexing real-time",
          "Niche edit volume besar di situs high-DR",
          "Target ranking 7-14 hari",
          "Monitoring real-time + dedicated handler",
          "Laporan harian + war-room strategi",
          "Disaster recovery plan kalau kena update"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Aset Link & Network",
        "items": [
          "PBN links dari jaringan privat dengan DA/DR terjaga",
          "Parasite SEO placement di platform high-authority",
          "Niche edit & contextual link di artikel relevan",
          "Anchor text strategy (exact, partial, branded, naked)",
          "Mass indexing report semua backlink terpasang"
        ]
      },
      {
        "title": "Ranking & Performa",
        "items": [
          "Tracking posisi semua target keyword",
          "Screenshot bukti ranking before-after",
          "Estimasi traffic & potensi konversi per keyword",
          "Analisa kompetitor halaman 1"
        ]
      },
      {
        "title": "Monitoring & Reporting",
        "items": [
          "Dashboard monitoring ranking (harian/mingguan sesuai paket)",
          "Alert otomatis kalau ada drop ranking",
          "Laporan link velocity & status indexing",
          "Rekomendasi langkah lanjutan tiap periode"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Audit & Risk Assessment",
        "desc": "Kami bedah keyword target, level kompetisi, dan profil situs kamu. Lalu kami tentukan strategi: churn-and-burn buat hasil instan, atau longterm yang lebih awet. Kamu dapat gambaran jujur soal risiko sebelum mulai.",
        "duration": "2-3 hari"
      },
      {
        "step": "02",
        "title": "Strategi & Mapping Link",
        "desc": "Kami susun blueprint: PBN tier mana, parasite platform apa, distribusi anchor text, dan target link velocity. Semua dirancang biar footprint minim dan momentum ranking maksimal.",
        "duration": "3-5 hari"
      },
      {
        "step": "03",
        "title": "Eksekusi Agresif",
        "desc": "Pemasangan PBN links, parasite SEO, dan niche edit dijalankan sesuai velocity yang terukur. Mass indexing langsung gas biar Google baca cepat. Di sini ranking mulai gerak.",
        "duration": "1-3 minggu"
      },
      {
        "step": "04",
        "title": "Monitoring & Stabilisasi",
        "desc": "Begitu masuk halaman 1, kami pantau harian, atur sisa velocity, dan jaga posisi tetap stabil. Kalau ada fluktuasi, kami langsung respons.",
        "duration": "Berjalan"
      },
      {
        "step": "05",
        "title": "Scale atau Burn",
        "desc": "Untuk longterm, kami perkuat aset dan ekspansi keyword. Untuk churn-and-burn, kami bantu maksimalin panen sebelum siklus berikutnya. Strategi kamu, keputusan kamu.",
        "duration": "Sesuai goal"
      }
    ],
    "stats": [
      {
        "value": "7-30 hari",
        "label": "Rata-rata waktu masuk halaman 1"
      },
      {
        "value": "Top 3",
        "label": "Posisi yang biasa dicapai keyword utama"
      },
      {
        "value": "500+",
        "label": "Keyword berhasil di-ranking-kan"
      },
      {
        "value": "Daily",
        "label": "Frekuensi monitoring & alert ranking"
      }
    ],
    "faqs": [
      {
        "q": "Berapa cepat keyword saya bisa masuk halaman 1?",
        "a": "Tergantung level kompetisi keyword. Untuk low-medium competition, biasanya 7-21 hari. Untuk niche super kompetitif, bisa 14-30 hari atau lebih. Kami selalu kasih estimasi realistis di tahap audit, bukan janji muluk-muluk."
      },
      {
        "q": "Industri saya ditolak agency lain. Apa kalian terima?",
        "a": "Kemungkinan besar iya. Kami terima berbagai industri, termasuk niche yang dianggap terlalu abu-abu oleh agency mainstream. Diskusi dulu di tahap konsultasi — kami akan jujur soal apakah niche kamu feasible dan strategi apa yang paling pas."
      },
      {
        "q": "Apa risiko sebenarnya dari black-hat SEO?",
        "a": "Risiko utamanya adalah penalti algoritma Google yang bisa bikin situs drop ranking atau ter-deindex. Karena itu black-hat paling cocok buat money site dan churn-and-burn, bukan brand utama yang mau kamu jaga puluhan tahun. Kami selalu jelasin risiko ini di depan dan bantu kamu pilih strategi yang sesuai toleransi risiko kamu."
      },
      {
        "q": "Ada garansi ranking gak?",
        "a": "Kami garansi effort dan deliverable konkret (jumlah link, indexing, monitoring), bukan posisi pasti — karena algoritma Google di luar kontrol siapa pun, termasuk kami. Yang kami janjikan: kalau target gak tercapai dalam periode tertentu, kami evaluasi ulang strategi dan lanjut optimasi tanpa biaya tambahan sesuai kesepakatan paket."
      },
      {
        "q": "Apakah identitas dan proyek saya dirahasiakan?",
        "a": "Ya. Anonimitas klien kami jaga ketat. Footprint teknis juga kami minimalisir biar jejak antar-situs gak gampang dilacak. Detail teknis spesifik kami simpan internal demi keamanan jaringan dan klien."
      },
      {
        "q": "Beda churn-and-burn sama longterm itu apa?",
        "a": "Churn-and-burn fokus hasil instan: ranking cepat, panen traffic/konversi maksimal dalam waktu singkat, lalu siap ganti domain kalau perlu. Cocok buat affiliate dan promo musiman. Longterm dirancang lebih hati-hati dengan velocity dan footprint yang lebih halus, supaya aset bertahan lebih lama. Kami bantu pilih sesuai goal kamu."
      },
      {
        "q": "Metode pembayarannya gimana?",
        "a": "Pembayaran bulanan di depan via transfer bank atau crypto untuk privasi tambahan. Untuk paket Brutal, ada opsi termin. Semua kesepakatan dituangkan jelas sebelum eksekusi dimulai."
      },
      {
        "q": "Kalau situs saya kena penalti, gimana?",
        "a": "Untuk paket Pro dan Brutal, kami sertakan disaster recovery plan: analisa penyebab, migrasi aset, atau pivot strategi. Tapi penting dipahami — dengan black-hat, risiko penalti gak pernah nol. Itu sebabnya kami sarankan jangan taruh brand utama kamu di sini."
      }
    ],
    "riskNote": "Black-hat SEO = high-risk, high-reward. Teknik agresif ini bisa kena penalti algoritma Google kapan saja, jadi cocok untuk money site, affiliate, dan strategi churn-and-burn — bukan brand utama jangka panjang. Kami transparan soal risikonya; keputusan akhir ada di tangan kamu."
  },
  "black-hat-ads": {
    "tagline": "Iklan tetap jalan, walau produknya \"susah lolos\".",
    "heroBadge": "⚠️ High-Risk High-Reward",
    "heroTitle": "Produk kamu sering kena banned?",
    "heroTitleHighlight": "Kita yang bikin iklannya tetap ngebut.",
    "heroSubtitle": "Buat kamu yang jualan produk gray-area dan capek akun iklan mati tiap minggu: kita sediain akun agency trusted, kelola kampanye biar tetap aktif, urus banding kalau kena, dan ganti akun secepat kilat begitu ada masalah. Lima platform sekaligus — Meta, Google, TikTok, Snack Video, Google Discovery — dengan satu tujuan: budget tetap kebakar ke arah yang benar, ROAS naik, omzet jalan.",
    "intro": [
      "Kamu udah tahu rasanya: scaling lagi enak-enaknya, ROAS lagi cakep, tiba-tiba akun di-disable dan semua momentum hilang. Produk kamu masuk kategori yang platform anggap sensitif — supplement, beauty claim agresif, layanan keuangan, gaming, atau niche lain yang ad reviewer-nya galak. Tim iklan biasa angkat tangan di sini. Kita enggak.",
      "Divisi Hitam Para Suhu Digital adalah unit khusus untuk produk high-risk. Kita main di akun agency dan trusted account dengan limit besar dan history bersih, kelola kampanye dengan disiplin biar nggak gampang dipencet, dan udah siapin akun cadangan dari hari pertama. Jadi kalau satu akun tumbang, kampanye kamu lompat ke akun baru dalam hitungan jam — bukan minggu.",
      "Kita jujur dari awal: ini bukan jalur aman jangka panjang dan kita nggak akan janji surga. Ini jalur agresif untuk kamu yang butuh volume cepat, berani ambil risiko, dan ngerti bahwa di dunia ini akun adalah barang habis pakai. Yang kita jamin: eksekusi rapi, akun pengganti selalu ready, dan angka yang transparan tiap minggu."
    ],
    "features": [
      "Akun agency & trusted account untuk 5 platform: Meta, Google, TikTok, Snack Video, Google Discovery",
      "Setup kampanye full-funnel khusus produk yang sulit di-approve",
      "Manajemen harian biar kampanye tetap aktif & spending stabil",
      "Handle banding/appeal saat akun atau iklan kena flag",
      "Pool akun cadangan ready — ganti akun cepat begitu kena, kampanye lanjut hari itu juga",
      "Scaling budget bertahap dari ratusan ribu sampai puluhan juta per hari",
      "Optimasi ROAS: cut yang boncos, gandakan yang profit",
      "Migrasi pixel, audience & data antar-akun biar learning nggak hangus",
      "Laporan transparan: spend, ROAS, status akun, sisa stok akun cadangan",
      "Manajer dedicated yang standby kalau ada akun tumbang mendadak"
    ],
    "packages": [
      {
        "name": "Starter Burn",
        "priceLabel": "Mulai Rp 7,5jt/bulan",
        "for": "Tes air, 1 platform, daily budget kecil-menengah. Buat kamu yang mau validasi produk gray-area sebelum gas pol.",
        "includes": [
          "1 platform pilihan (Meta / Google / TikTok / Snack Video / Discovery)",
          "1 akun agency/trusted aktif + 1 akun cadangan standby",
          "Setup kampanye + 3 set creative awal",
          "Manajemen harian & optimasi ROAS dasar",
          "Handle banding standar saat kena flag",
          "Ganti akun cepat 1x/bulan kalau tumbang",
          "Laporan mingguan: spend, ROAS, status akun"
        ],
        "popular": false
      },
      {
        "name": "Pro Scaler",
        "priceLabel": "Mulai Rp 18jt/bulan",
        "for": "Produk udah terbukti convert, siap scaling serius di 2-3 platform sekaligus dengan daily budget belasan juta. Pilihan paling banyak diambil.",
        "includes": [
          "2-3 platform jalan paralel",
          "Pool akun trusted + minimal 3 akun cadangan per platform",
          "Setup full-funnel + creative rotation rutin",
          "Optimasi ROAS harian + scaling budget bertahap",
          "Handle banding prioritas + migrasi pixel/audience antar-akun",
          "Ganti akun cepat unlimited (selama stok ready)",
          "Manajer dedicated + laporan 2x/minggu",
          "War room WhatsApp buat respons cepat saat akun kena"
        ],
        "popular": true
      },
      {
        "name": "Brutal Mode",
        "priceLabel": "Rp 40jt+/bulan",
        "for": "Gas maksimal di 5 platform, daily budget puluhan juta, target volume agresif. Buat money site & campaign churn-and-burn skala besar.",
        "includes": [
          "Semua 5 platform aktif serentak",
          "Pool akun trusted besar + cadangan dalam jumlah banyak",
          "Tim dedicated (media buyer + appeal specialist + creative)",
          "Scaling agresif sampai puluhan juta/hari",
          "Optimasi ROAS real-time + reallocation budget antar-platform",
          "Banding prioritas tertinggi + replace akun instan",
          "Strategi multi-akun & multi-domain rotation",
          "Laporan harian + standby 7 hari/minggu",
          "Konsultasi strategi exit sebelum akun \"panas\""
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Infrastruktur Akun",
        "items": [
          "Akun agency & trusted account dengan history bersih untuk tiap platform",
          "Pool akun cadangan yang udah di-warm-up dan siap pakai",
          "Setup pixel, tracking & domain verification per akun",
          "Rotasi & manajemen multi-akun biar nggak saling kena imbas"
        ]
      },
      {
        "title": "Manajemen & Optimasi Kampanye",
        "items": [
          "Setup kampanye full-funnel: prospecting, retargeting, scaling",
          "Optimasi ROAS harian — pause yang boncos, scale yang profit",
          "Scaling budget bertahap, dari ratusan ribu sampai puluhan juta/hari",
          "Creative rotation rutin biar fatigue & flag-rate ditekan"
        ]
      },
      {
        "title": "Survival & Recovery",
        "items": [
          "Handle banding/appeal tiap kali akun atau iklan kena flag",
          "Replace akun cepat — kampanye pindah ke akun baru di hari yang sama",
          "Migrasi audience, pixel & data biar fase learning nggak hangus",
          "Monitoring kesehatan akun: estimasi durasi bertahan & sinyal bahaya"
        ]
      },
      {
        "title": "Reporting & Komunikasi",
        "items": [
          "Laporan spend, ROAS, CPA & status tiap akun",
          "Update stok akun cadangan yang masih ready",
          "War room WhatsApp buat respons cepat saat akun mendadak tumbang",
          "Review strategi berkala + rekomendasi kapan harus rem atau gas"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Audit Produk & Risk Profiling",
        "desc": "Kita bedah produk, landing page, dan history akun kamu sebelumnya. Dari sini kita tentukan platform mana yang paling realistis, estimasi seberapa \"panas\" produknya, dan berapa banyak akun cadangan yang perlu disiapin.",
        "duration": "1-3 hari"
      },
      {
        "step": "02",
        "title": "Setup Akun & Infrastruktur",
        "desc": "Kita siapin akun agency/trusted plus pool cadangan, pasang pixel & tracking, dan verifikasi domain. Semua di-warm-up dulu biar nggak langsung dicurigai pas spending naik.",
        "duration": "3-7 hari"
      },
      {
        "step": "03",
        "title": "Launch & Stabilisasi",
        "desc": "Kampanye full-funnel kita gas dengan budget terukur. Fokus minggu awal: cari pemenang creative & audience sambil jaga akun tetap hidup dan stabil.",
        "duration": "Minggu 1-2"
      },
      {
        "step": "04",
        "title": "Scaling & Optimasi ROAS",
        "desc": "Begitu ada kombinasi yang profit, kita scale budget bertahap, reallocate ke platform yang paling cuan, dan rotasi creative biar performa nggak loyo. Target: ROAS naik konsisten tanpa bikin akun cepat panas.",
        "duration": "Berkelanjutan"
      },
      {
        "step": "05",
        "title": "Recovery & Replace Cycle",
        "desc": "Kalau akun kena, kita langsung ajukan banding dan paralel pindahin kampanye ke akun cadangan di hari yang sama. Tujuannya satu: downtime nyaris nol, momentum spending nggak putus.",
        "duration": "Same-day response"
      }
    ],
    "stats": [
      {
        "value": "5",
        "label": "Platform di-cover serentak"
      },
      {
        "value": "ROAS 3-7x",
        "label": "Range realistis di kampanye scaling"
      },
      {
        "value": "< 24 jam",
        "label": "Replace akun saat tumbang"
      },
      {
        "value": "Rp 50jt+/hari",
        "label": "Daily budget yang pernah di-handle"
      }
    ],
    "faqs": [
      {
        "q": "Produk gue sering banget kena banned. Kalian beneran bisa bikin iklannya jalan?",
        "a": "Bisa, dan itu memang spesialisasi kita. Bedanya bukan soal \"jurus rahasia\" instan, tapi infrastruktur: akun trusted dengan history bersih, manajemen kampanye yang disiplin biar nggak gampang dipencet, dan pool akun cadangan yang selalu ready. Jadi fokusnya bukan menjamin akun nggak pernah mati, tapi memastikan begitu mati, kampanye kamu langsung lanjut di akun lain tanpa kehilangan banyak momentum."
      },
      {
        "q": "Akunnya bisa bertahan berapa lama?",
        "a": "Jujur: tergantung produk, agresivitas scaling, dan platformnya. Untuk produk gray-area, umur akun bisa dari beberapa minggu sampai beberapa bulan. Justru karena itu kita kerja dengan asumsi akun = barang habis pakai dan selalu siapin cadangan. Yang kita optimalkan bukan umur satu akun, tapi total volume & profit yang bisa kamu tarik sebelum harus pindah."
      },
      {
        "q": "Berapa ROAS yang realistis?",
        "a": "Range yang sehat di kampanye scaling biasanya 3-7x, tergantung margin produk dan platform. Kita nggak akan janji ROAS dua digit yang nggak masuk akal. Yang kita lakukan: cut cepat kampanye yang boncos, gandakan yang profit, dan transparan soal angka tiap minggu biar kamu bisa hitung sendiri untung-ruginya."
      },
      {
        "q": "Kalau akun kena banding, berapa lama recovery-nya?",
        "a": "Banding kita ajukan secepatnya, tapi hasilnya di tangan platform — kadang menang, kadang nggak. Makanya kita nggak pernah cuma mengandalkan banding. Begitu satu akun tumbang, kampanye kamu kita pindahin ke akun cadangan di hari yang sama, jadi spending tetap jalan sambil banding diproses paralel."
      },
      {
        "q": "Ini legal dan aman buat brand gue nggak?",
        "a": "Ini jalur high-risk. Iklan agresif untuk produk yang sulit di-approve berarti kamu menerima kemungkinan akun di-disable, iklan ditolak, dan dalam kasus tertentu sanksi dari platform. Kita posisikan ini buat money site, dropship, atau campaign churn-and-burn — bukan buat brand utama yang reputasinya kamu jaga jangka panjang. Kalau kamu butuh jalur aman & berkelanjutan, kita arahkan ke divisi Putih kita."
      },
      {
        "q": "Gimana soal kerahasiaan? Gue nggak mau identitas gue kebawa-bawa.",
        "a": "Komunikasi bisa lewat kanal privat dan data kamu kita pegang seperlunya aja. Tapi kita transparan: nggak ada layanan iklan yang 100% anonim, karena platform tetap punya sistem tracking sendiri. Yang kita lakukan adalah memisahkan infrastruktur kampanye dari aset pribadi kamu sebisa mungkin."
      },
      {
        "q": "Sistem pembayarannya gimana? Ada garansi?",
        "a": "Fee manajemen dibayar di muka per bulan, terpisah dari ad spend (ad spend kamu yang tanggung langsung). Karena ini layanan high-risk, kita nggak kasih garansi akun-nggak-mati atau garansi ROAS — itu janji yang nggak jujur. Yang kita garansi: eksekusi sesuai paket, akun pengganti selalu kita usahakan ready, dan laporan transparan. Kalau di tengah jalan kamu mau stop, kita atur dengan jelas di kontrak."
      },
      {
        "q": "Bedanya sama jasa Suhu Ads yang biasa apa?",
        "a": "Suhu Ads (divisi Putih) main di akun & produk yang patuh policy, fokus brand jangka panjang dan akun yang stabil. Divisi Hitam ini khusus produk gray-area yang sering ditolak — kita main di akun trusted, siapin cadangan, dan jago recovery. Beda risiko, beda tujuan. Kalau ragu produk kamu masuk yang mana, konsultasi dulu, nanti kita kasih rekomendasi jujur."
      }
    ],
    "riskNote": "Black-hat ads = high-risk high-reward. Akun bisa di-disable kapan aja, banding nggak selalu menang, dan platform berhak kasih sanksi — jadi layanan ini cocok untuk money site, dropship, atau campaign churn-and-burn, bukan brand utama yang reputasinya kamu jaga jangka panjang. Kita jual eksekusi rapi & recovery cepat, bukan jaminan akun abadi atau ROAS ajaib."
  },
  "backlink": {
    "tagline": "Backlink power untuk dongkrak ranking, bukan sekadar nambah angka di Ahrefs.",
    "heroBadge": "⚡ Authority Injection — DA/DR 30-80+",
    "heroTitle": "Suntik authority ke money site kamu",
    "heroTitleHighlight": "sampai Google nggak punya alasan buat nahan ranking.",
    "heroSubtitle": "Tiga tipe backlink, satu tujuan: ngangkat domain authority dan posisi keyword kamu lebih cepat dari kompetitor. Hidden backlink dari situs authority, blogroll sitewide di ribuan halaman, plus blogpost contextual dofollow — semua dengan situs DA/DR jelas, indexing rate tinggi, retensi terukur, dan laporan transparan. Kamu fokus konversi, kita yang urus link juice.",
    "intro": [
      "Ranking di Google itu kompetisi authority. Kompetitor kamu mungkin udah punya ratusan backlink dengan jam terbang bertahun-tahun, dan kamu butuh ngejar itu tanpa nunggu organik selama 12 bulan. Di sinilah jasa backlink agresif main: kita pompa link juice dari situs-situs ber-authority langsung ke money site kamu, dengan struktur yang dirancang buat ngedorong keyword spesifik naik kelas.",
      "Kita nggak jual \"1000 backlink Rp50rb\" yang isinya spam komentar dan link mati seminggu kemudian. Yang kita kerjain adalah link dari situs dengan DA/DR terverifikasi, traffic real, dan retensi yang kita garansi hitam di atas putih. Tiga produk utama — Hidden Backlink, Blogroll, dan Blogpost — punya karakter dan use case berbeda, dan kita bantu kamu racik kombinasinya sesuai target keyword dan profil risiko.",
      "Jujur dari awal: ini divisi Hitam. Pendekatan kita high-risk high-reward, cocok buat money site, niche kompetitif, dan strategi churn-and-burn yang butuh hasil cepat. Kalau kamu siap main agresif buat hasil yang juga agresif, kita partner yang tepat."
    ],
    "features": [
      "Situs authority terverifikasi DA/DR 30-80+, bukan PBN abal-abal",
      "3 tipe link: Hidden, Blogroll, Blogpost — bisa dikombinasi",
      "Mayoritas dofollow, link juice langsung ngalir ke target",
      "Indexing rate 85-95% lewat push indexing aktif",
      "Retensi link digaransi 3-12 bulan tergantung paket",
      "Anchor text mix natural: exact, partial, branded, generic",
      "Drip-feed delivery biar link velocity keliatan organik",
      "Laporan lengkap: URL hidup, DA/DR, status index, screenshot",
      "Topical relevance — situs penempatan sesuai niche kamu",
      "Ganti gratis kalau ada link drop dalam masa garansi"
    ],
    "packages": [
      {
        "name": "Starter Boost",
        "priceLabel": "Mulai Rp 1,5jt",
        "for": "Money site baru / niche ringan yang butuh fondasi authority awal",
        "includes": [
          "10 Blogpost dofollow di situs DA/DR 20-40",
          "Artikel 500+ kata, 1 contextual link per artikel",
          "Anchor text natural mix",
          "Indexing rate target 85%+",
          "Retensi garansi 3 bulan",
          "Laporan URL hidup + DA/DR (Google Sheet)"
        ],
        "popular": false
      },
      {
        "name": "Pro Authority",
        "priceLabel": "Mulai Rp 6,5jt",
        "for": "Money site di niche kompetitif yang mau lompat halaman 1 cepat",
        "includes": [
          "25 Blogpost dofollow di situs DA/DR 30-60",
          "5 Hidden Backlink di situs authority/expired DA/DR 40+",
          "1 paket Blogroll sitewide (1.000+ halaman) selama 3 bulan",
          "Artikel 700+ kata, contextual dofollow",
          "Drip-feed 3-4 minggu biar velocity natural",
          "Indexing rate target 90%+, push indexing aktif",
          "Retensi garansi 6 bulan + ganti gratis kalau drop",
          "Laporan bulanan + konsultasi anchor & target keyword"
        ],
        "popular": true
      },
      {
        "name": "Brutal Dominance",
        "priceLabel": "Rp 25jt+",
        "for": "Niche gambling/finance/agresif yang mau dominasi SERP & gusur kompetitor",
        "includes": [
          "50+ Blogpost dofollow di situs DA/DR 40-80",
          "15+ Hidden Backlink di situs authority/expired DA/DR 50+",
          "Blogroll sitewide multi-situs (5.000+ halaman) selama 6 bulan",
          "Tiered link structure (Tier 1 + Tier 2 booster)",
          "Custom anchor & landing strategy per keyword cluster",
          "Indexing rate target 95%+ dengan indexing service premium",
          "Retensi garansi 12 bulan + priority replacement",
          "Dedicated account manager + laporan dwi-mingguan"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Hidden Backlink — link tersembunyi di situs authority",
        "items": [
          "Link disisipkan di situs authority aktif & domain expired ber-DA/DR tinggi (40-80+)",
          "Penempatan tersembunyi yang tetap di-crawl & meneruskan link juice ke target",
          "Mayoritas dofollow, anchor text exact/partial sesuai keyword prioritas",
          "Indexing rate target 90-95% dengan push indexing",
          "Retensi 6-12 bulan tergantung paket, dengan replacement guarantee",
          "Laporan: URL host, DA/DR, status dofollow, status index"
        ]
      },
      {
        "title": "Blogroll — link sitewide di ribuan halaman",
        "items": [
          "Link dipasang di sidebar/footer sehingga muncul sitewide di seluruh halaman situs",
          "Volume tayang masif: 1.000 sampai 5.000+ halaman per situs",
          "Dofollow sitewide — link equity terdistribusi ke seluruh internal page",
          "Durasi sewa fleksibel: 3 atau 6 bulan, bisa diperpanjang",
          "Cocok buat ngangkat DA/DR domain & boosting keyword head term",
          "Laporan: domain host, estimasi jumlah halaman, DA/DR, screenshot penempatan"
        ]
      },
      {
        "title": "Blogpost — artikel berkualitas + contextual dofollow",
        "items": [
          "Artikel original 500-700+ kata, relevan secara topical dengan niche kamu",
          "1 contextual dofollow link disisipkan natural di dalam body artikel",
          "Situs penempatan DA/DR 20-80 sesuai paket, traffic real",
          "Anchor text mix natural untuk profil link yang aman",
          "Indexing rate target 85-95%, drip-feed delivery",
          "Laporan: URL artikel hidup, DA/DR, anchor, tanggal publish"
        ]
      },
      {
        "title": "Reporting & garansi",
        "items": [
          "Laporan terstruktur via Google Sheet: semua URL bisa diklik & diverifikasi",
          "Data per link: DA/DR, dofollow/nofollow, status index, tanggal tayang",
          "Monitoring retensi berkala selama masa garansi",
          "Replacement gratis untuk link yang drop sebelum masa garansi habis",
          "Konsultasi strategi anchor text & target keyword (paket Pro & Brutal)"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Audit & strategi target",
        "desc": "Kita bedah profil backlink kamu sekarang, keyword target, dan kompetitor. Dari situ kita tentukan mix tipe link (Hidden/Blogroll/Blogpost), volume, dan anchor text plan yang aman tapi agresif.",
        "duration": "1-2 hari"
      },
      {
        "step": "02",
        "title": "Seleksi situs penempatan",
        "desc": "Kita pilih situs host sesuai DA/DR target, relevansi niche, dan traffic real. Kamu dapat preview daftar metrik sebelum eksekusi — bukan kucing dalam karung.",
        "duration": "2-3 hari"
      },
      {
        "step": "03",
        "title": "Eksekusi & drip-feed",
        "desc": "Link dipasang bertahap (drip-feed) biar link velocity keliatan natural di mata Google. Artikel ditulis, hidden link disisipkan, blogroll diaktifkan sesuai timeline paket.",
        "duration": "1-4 minggu"
      },
      {
        "step": "04",
        "title": "Push indexing",
        "desc": "Setiap link kita dorong masuk index lewat indexing service aktif sampai nyentuh target rate 85-95%. Link yang nggak ke-index = link sia-sia, jadi tahap ini wajib.",
        "duration": "3-10 hari"
      },
      {
        "step": "05",
        "title": "Laporan & monitoring retensi",
        "desc": "Kamu terima laporan lengkap berisi semua URL hidup, DA/DR, status index, dan screenshot. Selama masa garansi kita pantau retensi dan ganti link yang drop tanpa biaya tambahan.",
        "duration": "Berkelanjutan"
      }
    ],
    "stats": [
      {
        "value": "DA/DR 80+",
        "label": "Authority situs penempatan tertinggi"
      },
      {
        "value": "95%",
        "label": "Indexing rate dengan push indexing premium"
      },
      {
        "value": "5.000+",
        "label": "Halaman tayang per situs blogroll"
      },
      {
        "value": "12 bln",
        "label": "Retensi link maksimal dengan garansi"
      }
    ],
    "faqs": [
      {
        "q": "Apa beda Hidden Backlink, Blogroll, dan Blogpost?",
        "a": "Hidden Backlink = link tersembunyi yang disisipkan di situs authority atau domain expired ber-DA/DR tinggi, tetap di-crawl Google dan meneruskan link juice. Blogroll = link sitewide di sidebar/footer yang muncul di ribuan halaman sekaligus, ampuh buat ngangkat authority domain. Blogpost = artikel original berkualitas dengan 1 contextual dofollow link di dalam body — paling natural dan paling aman secara profil. Banyak klien kombinasikan ketiganya buat efek maksimal."
      },
      {
        "q": "Linknya dofollow atau nofollow?",
        "a": "Mayoritas dofollow, karena dofollow yang meneruskan link equity dan ngangkat ranking. Tapi profil link yang sehat butuh sedikit campuran nofollow biar keliatan natural. Komposisinya kita atur otomatis di setiap paket, dan status dofollow/nofollow setiap link kita cantumkan jelas di laporan."
      },
      {
        "q": "Berapa lama linknya bertahan (retensi)?",
        "a": "Tergantung paket: Starter garansi 3 bulan, Pro 6 bulan, Brutal 12 bulan. Selama masa garansi, kalau ada link yang drop atau hilang, kita ganti gratis. Setelah garansi habis, kamu bisa perpanjang sewa (khusus blogroll) atau biarkan — banyak blogpost dan hidden link tetap bertahan jauh lebih lama dari masa garansinya."
      },
      {
        "q": "Indexing rate-nya seberapa tinggi?",
        "a": "Target kami 85-95% tergantung paket. Link yang nggak ke-index sama aja nggak ada nilainya, jadi setiap link kita dorong lewat push indexing aktif sampai masuk index. Status index per link bisa kamu verifikasi sendiri di laporan."
      },
      {
        "q": "Ini aman buat website saya? Apa risikonya?",
        "a": "Ini layanan divisi Hitam — pendekatannya agresif dan high-risk. Backlink agresif bisa ngangkat ranking jauh lebih cepat, tapi selalu ada risiko algorithm update atau manual action dari Google. Makanya kita pakai drip-feed, anchor text natural mix, dan situs ber-authority real buat minimalisir jejak. Tetap saja, ini paling cocok buat money site / churn-and-burn, bukan brand korporat yang nggak boleh ada risiko sama sekali."
      },
      {
        "q": "Apakah identitas dan project saya dijaga rahasia?",
        "a": "Iya. Kita jaga kerahasiaan penuh — target URL, keyword, dan data project kamu nggak pernah kita bagikan atau pakai sebagai portofolio publik tanpa izin. Privasi klien divisi Hitam adalah standar baku kami."
      },
      {
        "q": "Pembayarannya gimana? Bisa cicil?",
        "a": "Untuk Starter dan Pro, pembayaran di muka sebelum eksekusi. Untuk Brutal Dominance yang berjalan multi-bulan, bisa diatur termin (misalnya 50% di muka, sisanya bertahap). Kita terima transfer bank dan beberapa metode lain — detail dibahas saat konsultasi."
      },
      {
        "q": "Ada garansi naik ranking?",
        "a": "Kita garansi deliverable-nya: jumlah link, DA/DR situs, indexing rate, dan retensi sesuai paket — semua terverifikasi di laporan. Soal posisi ranking, kita nggak bisa janji angka pasti karena dipengaruhi banyak faktor di luar backlink (kualitas on-page, kompetisi, algoritma). Yang kita garansi adalah authority dan link juice yang masuk ke site kamu nyata dan terukur."
      }
    ],
    "riskNote": "Layanan ini black-hat dengan profil high-risk high-reward: backlink agresif bisa ngangkat ranking cepat, tapi tetap berisiko terkena algorithm update atau manual action Google. Paling cocok untuk money site dan strategi churn-and-burn, bukan brand jangka panjang yang nol-toleransi terhadap risiko."
  },
  "landing-page": {
    "tagline": "Landing page kilat yang siap tempur buat campaign ads paling agresif.",
    "heroBadge": "⚡ Load <1 Detik · Anti-Banned",
    "heroTitle": "Landing Page AMP yang nge-load",
    "heroTitleHighlight": "sebelum jempol kamu sempat scroll.",
    "heroSubtitle": "Untuk kamu yang main di traffic mahal dan volume gede: setiap 100ms delay itu duit yang nguap. Kami bangun LP super ringan berbasis AMP — prelander, money page, A/B variant, hosting bulletproof — yang siap nelan traffic ads agresif tanpa loading lemot dan tanpa LP gampang tumbang.",
    "intro": [
      "Kalau kamu jalanin campaign di niche gambling, finance, health, atau affiliate, kamu tahu masalahnya bukan cuma bikin LP cantik. Masalahnya: LP harus nge-load instan biar bounce rate gak bunuh ROAS, harus tahan banting biar gak tumbang pas trafik lagi panas, dan harus convert dingin-dingin dari klik pertama. Landing page biasa yang berat 3 detik? Itu kuburan budget.",
      "Kami fokus di satu hal: kecepatan eksekusi dan kecepatan halaman. AMP page yang load di bawah 1 detik, prelander/safe page yang nyaringin trafik, money page yang dioptimasi habis-habisan buat konversi, plus copywriting yang ditulis buat ngegerakin orang ambil tindakan — bukan buat dikagumi. Semua mobile-first, karena 90%+ trafik ads kamu dari HP.",
      "Ini layanan high-risk high-reward. Cocok buat money site dan campaign churn-and-burn yang butuh LP cepat jadi, cepat live, dan tahan tekanan. Kami kasih kamu mesin konversi yang ngebut — strategi distribusi trafik dan kepatuhan platform tetap ada di tangan kamu."
    ],
    "features": [
      "AMP page murni, render <1 detik bahkan di koneksi 3G",
      "Prelander / safe page buat warming & filter kualitas trafik",
      "Money page dengan funnel konversi yang diasah per niche",
      "Copywriting konversi tinggi: headline, hook, CTA yang nendang",
      "Hosting bulletproof anti-banned dengan uptime tinggi",
      "A/B variant siap pakai buat split-test angle & offer",
      "Mobile-first 100%, lulus Core Web Vitals di zona hijau",
      "Tracking & pixel siap pasang (Meta, TikTok, Google, custom postback)",
      "Struktur ringan: zero bloat, zero script sampah",
      "Deploy kilat — LP pertama bisa live dalam hitungan hari"
    ],
    "packages": [
      {
        "name": "Sprint",
        "priceLabel": "Mulai Rp 3,5jt",
        "for": "Solo affiliate / single offer yang butuh 1 LP cepat live",
        "includes": [
          "1 AMP money page conversion-optimized",
          "Copywriting konversi (1 angle)",
          "Mobile-first responsive",
          "Setup tracking & pixel dasar",
          "Loading <1 detik tergaransi",
          "Hosting standar 1 bulan"
        ],
        "popular": false
      },
      {
        "name": "Blitz",
        "priceLabel": "Mulai Rp 8,5jt",
        "for": "Media buyer aktif yang butuh prelander + money page + split-test",
        "includes": [
          "Prelander/safe page + money page",
          "Copywriting konversi (hingga 3 angle)",
          "2 A/B variant siap split-test",
          "Hosting bulletproof anti-banned",
          "Tracking lengkap + postback affiliate",
          "Core Web Vitals hijau + audit speed",
          "Revisi cepat 2x dalam 14 hari"
        ],
        "popular": true
      },
      {
        "name": "Brutal",
        "priceLabel": "Rp 25jt+",
        "for": "Tim agresif & high-volume buyer yang gas banyak offer sekaligus",
        "includes": [
          "Multi-LP system (prelander + multi money page)",
          "Copywriting konversi unlimited angle",
          "A/B variant scalable + framework testing",
          "Hosting bulletproof premium, multi-domain",
          "Funnel & tracking arsitektur custom",
          "Dashboard performa + monitoring uptime",
          "Priority deploy + revisi cepat 30 hari",
          "Konsultasi optimasi konversi mingguan"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Aset Halaman",
        "items": [
          "File AMP page valid & lulus AMP test",
          "Prelander/safe page siap live",
          "Money page conversion-optimized",
          "Set A/B variant per angle/offer",
          "Source file + akses edit"
        ]
      },
      {
        "title": "Copy & Konversi",
        "items": [
          "Headline & sub-headline bertingkat",
          "Body copy persuasif per angle",
          "CTA & microcopy yang dioptimasi",
          "Struktur funnel dari hook ke closing"
        ]
      },
      {
        "title": "Infrastruktur & Tracking",
        "items": [
          "Hosting bulletproof anti-banned + domain pointing",
          "Setup pixel (Meta, TikTok, Google)",
          "Postback & event tracking affiliate",
          "Laporan speed (PageSpeed / Core Web Vitals)",
          "Panduan deploy & rollover variant"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Brief & Recon",
        "desc": "Kami bedah offer, niche, target trafik, dan angle. Kamu kasih akses tracker & aset; kami susun blueprint LP dan struktur funnel.",
        "duration": "1-2 hari"
      },
      {
        "step": "02",
        "title": "Copy & Desain Konversi",
        "desc": "Tim copywriter racik headline, hook, dan CTA. Desain mobile-first disusun ringan tanpa elemen yang bikin lemot.",
        "duration": "2-4 hari"
      },
      {
        "step": "03",
        "title": "Build AMP & Setup Hosting",
        "desc": "Halaman dibangun murni AMP, divalidasi, lalu di-deploy ke hosting bulletproof. Tracking & pixel dipasang dan dites.",
        "duration": "2-3 hari"
      },
      {
        "step": "04",
        "title": "QA Speed & A/B Variant",
        "desc": "Uji load <1 detik di berbagai device, validasi Core Web Vitals, siapkan A/B variant buat split-test angle.",
        "duration": "1-2 hari"
      },
      {
        "step": "05",
        "title": "Go-Live & Optimasi",
        "desc": "LP live dan siap nelan trafik. Kami pantau performa, bantu rotasi variant, dan tuning konversi sesuai paket.",
        "duration": "Ongoing"
      }
    ],
    "stats": [
      {
        "value": "<1 detik",
        "label": "Waktu load LP di mobile"
      },
      {
        "value": "3-7 hari",
        "label": "LP pertama live & siap gas"
      },
      {
        "value": "90+",
        "label": "Skor PageSpeed mobile rata-rata"
      },
      {
        "value": "99,9%",
        "label": "Uptime hosting bulletproof"
      }
    ],
    "faqs": [
      {
        "q": "AMP itu apa dan kenapa penting buat campaign ads?",
        "a": "AMP (Accelerated Mobile Pages) adalah format halaman super ringan yang render hampir instan di mobile. Buat campaign ads, ini krusial: makin cepat LP load, makin kecil bounce rate, makin tinggi konversi, dan makin sehat ROAS kamu. Trafik ads itu mahal — kamu gak mau kehilangan klik gara-gara loading lemot."
      },
      {
        "q": "Apa beda prelander, safe page, dan money page?",
        "a": "Prelander/safe page adalah halaman antara buat warming trafik dan nyaringin pengunjung sebelum mereka masuk ke money page — halaman utama tempat konversi terjadi. Kombinasi keduanya bikin funnel kamu lebih bersih dan angka konversi lebih stabil."
      },
      {
        "q": "Hosting bulletproof beneran anti-banned?",
        "a": "Kami pakai infrastruktur hosting yang dirancang tahan banting dengan uptime tinggi, cocok buat niche berisiko. Tapi jujur: tidak ada yang 100% kebal. 'Anti-banned' artinya jauh lebih tahan dan stabil dibanding hosting biasa, bukan jaminan mutlak. Kami transparan soal ini di depan."
      },
      {
        "q": "Apakah kalian kasih instruksi cloaking atau cara ngakalin deteksi platform?",
        "a": "Tidak. Kami bangun aset LP cepat, konversi tinggi, dan tahan banting — itu fokus kami. Strategi distribusi trafik dan kepatuhan terhadap kebijakan platform sepenuhnya tanggung jawab dan keputusan kamu sebagai operator campaign."
      },
      {
        "q": "Ada garansi konversi?",
        "a": "Kami garansi deliverable teknis: load <1 detik, AMP valid, mobile-first, dan A/B variant siap pakai. Soal angka konversi, itu dipengaruhi offer, kualitas trafik, dan angle kamu — yang kami pegang adalah ngasih mesin LP terbaik plus framework testing biar kamu bisa optimasi cepat."
      },
      {
        "q": "Gimana soal anonimitas dan kerahasiaan project?",
        "a": "Kerahasiaan dijaga penuh. Detail offer, niche, dan campaign kamu tidak kami bagikan ke pihak ketiga atau dijadikan portfolio publik tanpa izin. Komunikasi bisa lewat channel terenkripsi sesuai preferensi kamu."
      },
      {
        "q": "Pembayaran gimana? Bisa crypto?",
        "a": "Kami terima transfer bank dan e-wallet. Untuk crypto (USDT/BTC) bisa diatur per kesepakatan. Skema standar: DP di awal buat mulai build, pelunasan sebelum LP final di-handover dan di-deploy."
      },
      {
        "q": "Berapa cepat LP bisa live?",
        "a": "LP pertama biasanya live dalam 3-7 hari kerja tergantung paket dan kompleksitas funnel. Paket Brutal dapat priority deploy biar kamu bisa gas multiple offer lebih cepat."
      }
    ],
    "riskNote": "Layanan ini high-risk high-reward, didesain buat money site dan campaign churn-and-burn — bukan brand jangka panjang. Kamu bertanggung jawab penuh atas legalitas offer, kepatuhan platform, dan regulasi di wilayah operasi kamu; kami menyediakan aset teknis, bukan jaminan hasil atau nasihat hukum."
  },
  "tutoring": {
    "tagline": "Belajar langsung dari yang praktiknya jalan — bukan teori YouTube basi.",
    "heroBadge": "🎓 1-on-1 & Group Mentoring",
    "heroTitle": "Kuasai sendiri ilmu black-hat",
    "heroTitleHighlight": "yang gak diajarin di mana pun.",
    "heroSubtitle": "Mau bisa eksekusi ads anti-banned, SEO agresif, atau bangun backlink & main aged domain sendiri? Kami ajarin langsung, step-by-step, dengan materi yang disesuaikan sama kebutuhan & level kamu. Ads, SEO, backlink, cloaking-friendly funnel — pilih topiknya, kami bongkar semua.",
    "intro": [
      "Banyak yang mau terjun ke black-hat tapi bingung mulai dari mana — kursus online isinya teori basi, grup isinya jualan, dan yang beneran praktik jarang mau buka ilmu. Di sini beda: kamu belajar langsung dari tim yang tiap hari ngejalanin campaign nyata.",
      "Materinya 100% disesuaikan. Mau fokus ke Meta Ads yang tahan banned, parasite SEO, jaringan PBN, atau cara baca metrik aged domain biar gak ketipu — tinggal bilang. Kami susun kurikulum sesuai target, level, dan budget kamu. Sesi privat 1-on-1 atau grup kecil."
    ],
    "features": [
      "Materi disesuaikan: ads / SEO / backlink / aged domain / funnel",
      "Mentor praktisi aktif, bukan teori doang",
      "Sesi 1-on-1 atau grup kecil (online)",
      "Studi kasus campaign & SERP nyata",
      "Template, tools, & SOP yang kami pakai sendiri",
      "Grup tanya-jawab pasca-sesi",
      "Roadmap belajar sesuai level & target kamu"
    ],
    "packages": [
      {
        "name": "Sesi Privat",
        "priceLabel": "Hubungi Kami",
        "for": "1-on-1, 1 topik spesifik (mis. Meta Ads anti-banned atau audit aged domain)",
        "includes": [
          "Sesi privat 1-on-1 (online)",
          "1 topik fokus pilihan kamu",
          "Rekaman sesi + catatan materi",
          "Q&A 7 hari pasca-sesi"
        ],
        "popular": false
      },
      {
        "name": "Mentoring Bulanan",
        "priceLabel": "Hubungi Kami",
        "for": "Pendampingan rutin sambil kamu jalanin project sendiri",
        "includes": [
          "4 sesi/bulan (privat atau grup)",
          "Kurikulum custom sesuai target",
          "Review project & campaign kamu",
          "Akses grup tanya-jawab prioritas",
          "Template, tools, & SOP siap pakai",
          "Roadmap belajar bertahap"
        ],
        "popular": true
      },
      {
        "name": "Bootcamp Intensif",
        "priceLabel": "Hubungi Kami",
        "for": "Gas cepat dari nol sampai bisa eksekusi sendiri, multi-topik",
        "includes": [
          "Program intensif multi-topik (ads + SEO + backlink)",
          "Sesi privat + praktik langsung",
          "Setup tools & akun bareng mentor",
          "Studi kasus end-to-end",
          "Pendampingan sampai live campaign pertama",
          "Akses grup alumni"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Materi & Kurikulum",
        "items": [
          "Kurikulum custom sesuai topik & level",
          "Slide / dokumen materi tiap sesi",
          "Rekaman semua sesi",
          "Template, checklist & SOP siap pakai"
        ]
      },
      {
        "title": "Pendampingan",
        "items": [
          "Review project & akun kamu langsung",
          "Q&A pasca-sesi via grup",
          "Rekomendasi tools & resource",
          "Roadmap belajar lanjutan"
        ]
      }
    ],
    "process": [
      { "step": "01", "title": "Konsultasi Awal", "desc": "Cerita target, level, dan topik yang mau dikuasai. Kami petakan kebutuhan & susun rencana belajar.", "duration": "Hari 1" },
      { "step": "02", "title": "Susun Kurikulum", "desc": "Kami bikin kurikulum custom + jadwal sesi sesuai pace kamu. Materi & tools disiapkan.", "duration": "Hari 1-3" },
      { "step": "03", "title": "Sesi Mentoring", "desc": "Belajar langsung step-by-step: konsep, demo praktik nyata, lalu latihan di project kamu sendiri.", "duration": "Sesuai paket" },
      { "step": "04", "title": "Praktik & Review", "desc": "Kamu eksekusi, kami review hasilnya, koreksi, dan dampingi sampai kamu bisa jalan sendiri.", "duration": "Ongoing" }
    ],
    "stats": [
      { "value": "1-on-1", "label": "Privat atau grup kecil" },
      { "value": "100%", "label": "Materi disesuaikan" },
      { "value": "Praktisi", "label": "Mentor yang beneran jalan" },
      { "value": "All-topic", "label": "Ads, SEO, backlink, domain" }
    ],
    "faqs": [
      { "q": "Topik apa aja yang bisa diajarin?", "a": "Bebas sesuai kebutuhan: Meta/Google/TikTok Ads anti-banned, black hat SEO (PBN, parasite, mass index), teknik backlink, cara baca & audit aged domain, sampai bikin funnel/landing page cloaking-friendly. Tinggal bilang fokusnya, kami sesuaikan." },
      { "q": "Cocok buat pemula total?", "a": "Cocok. Kurikulum disusun sesuai level kamu — kalau dari nol, kami mulai dari fundamental dulu baru naik ke teknik agresif. Kalau udah jalan, kami fokus ke optimasi & scaling." },
      { "q": "Online atau offline?", "a": "Mayoritas online (video call) biar fleksibel & rekaman bisa kamu simpan. Sesi privat terjadwal sesuai kesepakatan. Offline bisa diatur khusus, tanya via WhatsApp." },
      { "q": "Berapa harganya?", "a": "Tergantung topik, format (privat/grup), dan durasi. Chat kami via WhatsApp dengan kebutuhan kamu, nanti kami kasih penawaran yang pas." },
      { "q": "Ilmunya beneran dibuka, gak ditutup-tutupi?", "a": "Iya. Justru itu bedanya — kami bongkar workflow, tools, dan SOP yang kami pakai sendiri, bukan teori umum. Tujuannya kamu bener-bener bisa eksekusi sendiri." }
    ],
    "riskNote": "Black-hat itu high-risk. Mentoring ini ngajarin teknik plus cara manajemen risikonya, tapi keputusan & tanggung jawab eksekusi tetap di tangan kamu."
  }
};

export const SERVICES: ServiceContent[] = SERVICE_META.map((m) => ({
  ...m,
  ...CONTENT[m.slug],
}));

export function getService(slug: string): ServiceContent | undefined {
  return SERVICES.find((s) => s.slug === slug);
}

export function serviceSlugs(): string[] {
  return SERVICE_META.map((m) => m.slug);
}
