// AUTO-GENERATED by scripts/gen-en-content.mjs — English service content.
import type { ServiceContent } from "./types";

type ServiceBody = Omit<
  ServiceContent,
  "slug" | "name" | "icon" | "accent" | "short"
>;

export const CONTENT_EN: Record<string, ServiceBody> = {
  "hunting-aged-domain": {
    "tagline": "Custom aged domains, hunted to your brief — no leftover stock, no faked metrics.",
    "heroBadge": "🔒 Clean History Guaranteed",
    "heroTitle": "Clean aged domains,",
    "heroTitleHighlight": "hunted specifically for your money site.",
    "heroSubtitle": "Give us the brief: niche, target DA/DR, language, and the history you want. We hunt the candidates one by one, audit their history and backlinks to the bone, verify the real metrics across Ahrefs + Moz + Majestic, then hand over a clean, ready-to-use domain. Not some random domain from a marketplace stock list — this is on-demand hunting, curated specifically for your ranking targets.",
    "intro": [
      "Authority takes years to build. An aged domain shortcuts that path. But 90% of the aged domains floating around out there are traps: lingering gambling/adult history, toxic backlinks, DR metrics pumped with a cheap PBN, or a deindex status you won't catch until you've already paid. Buy the wrong one and instead of climbing the rankings, your money site gets dragged down with it.",
      "This is where on-demand hunting differs from buying stock. We don't hand you a list of leftover domains already held by 50 other people. We start from your brief — what niche, what target DA/DR, what language, how clean the history needs to be — then go hunt candidates that genuinely fit. Every candidate goes through a history audit (Wayback Machine, dropped records, index status), a spam & toxic backlink audit, and a cross-verification of metrics across three tools at once so you never get fooled by inflated numbers.",
      "What you get at the end: a clean domain, real metrics you can re-check yourself, plus full audit documentation. And if the core metrics drop significantly within the warranty period, we replace it. This is the safe way to play aged domains without becoming the victim of a seller who's only selling you numbers."
    ],
    "features": [
      "100% custom hunting to your brief — your niche, DA/DR, language, and history call the shots",
      "Cross-verified metrics across 3 tools: Ahrefs (DR), Moz (DA), Majestic (TF/CF)",
      "Full history audit via Wayback Machine — checking for ex-gambling, adult, casino, scam content",
      "Inflated & PBN-pumped metric detection before you pay",
      "Toxic & spam backlink audit, plus a disavow-ready list",
      "Google index status check & dropped/deindex history of the domain",
      "Healthy Trust Flow / Citation Flow ratio (not a link farm)",
      "Replacement warranty if the core metrics drop within the warranty period",
      "Complete hand-over: domain + audit report + raw metric data",
      "Domain exclusive to you — never resold to another client"
    ],
    "packages": [
      {
        "name": "Solo Hunt",
        "priceLabel": "From Rp 1.5M",
        "for": "1 target domain to your brief, general niche, mid-range DA/DR — for testing the waters or a single money site",
        "includes": [
          "1 aged domain to your brief",
          "Mid-range DA/DR target (DR 15-30)",
          "Basic history audit (Wayback + index status)",
          "Metric verification via Ahrefs",
          "Quick spam score & toxic backlink check",
          "Concise audit report (PDF)",
          "14-day replacement warranty if metrics drop"
        ],
        "popular": false
      },
      {
        "name": "Pro Hunt",
        "priceLabel": "From Rp 4.5M",
        "for": "Bundle of 3 curated domains, specific niche, high DA/DR target & strict clean history — for scaling a PBN or a cluster of money sites",
        "includes": [
          "3 curated aged domains to your brief",
          "High DA/DR target (DR 30-50)",
          "Specific niche & language to order",
          "Full history audit (Wayback + dropped records + deindex check)",
          "Cross-verification across 3 tools (Ahrefs + Moz + Majestic)",
          "Toxic backlink audit + disavow-ready list",
          "Full audit report + raw metric data per domain",
          "30-day replacement warranty",
          "Priority turnaround"
        ],
        "popular": true
      },
      {
        "name": "Authority Hunt",
        "priceLabel": "Rp 12M+",
        "for": "High-DR / ultra-tough niche / large volume, ultra-clean history & premium metrics — for agencies, resellers, or brand-grade money sites",
        "includes": [
          "High-DR domains (DR 50+) or ultra-tough niches",
          "Custom volume (5, 10, 20+ domains)",
          "Forensic history audit (full timeline + manual review)",
          "Cross-verification across 3 tools + manual backlink spot-checks",
          "Deep link profile & anchor text analysis + topical/geo match",
          "Full forensic report per domain + usage recommendations",
          "60-day replacement warranty",
          "Dedicated handler + deployment strategy consultation",
          "Reseller / white-label rates available"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Per-Domain Audit Report",
        "items": [
          "Complete history timeline from the Wayback Machine (screenshot evidence of every era)",
          "Clean history verification — free of gambling, adult, casino, scam, and spam content",
          "Current Google index status + dropped/deindex history",
          "Spam score & toxic backlink ratio with clear red flags",
          "Verdict: safe to use, needs disavow, or skip it"
        ]
      },
      {
        "title": "Real Metric Verification (Anti-Inflation)",
        "items": [
          "DR (Ahrefs) + dashboard screenshot as proof",
          "DA & PA (Moz) cross-check",
          "Trust Flow & Citation Flow (Majestic) + healthy TF/CF ratio",
          "Real referring domains vs link farm — clearly distinguished",
          "Notes flagging PBN-pumped or artificial metrics if any are found"
        ]
      },
      {
        "title": "Backlink & Link Profile",
        "items": [
          "List of referring domains along with their quality",
          "Anchor text distribution (checked for over-optimization)",
          "Flagged toxic & spam links + disavow-ready list (.txt)",
          "Backlink topical relevance to your target niche",
          "Backlink geo-distribution (relevant for geo-targeting)"
        ]
      },
      {
        "title": "Hand-Over & Ownership",
        "items": [
          "Domain reclaimed/registered under your name — full ownership",
          "Guide to transfer/push to your registrar of choice",
          "Raw metric data (export) so you can re-check it yourself",
          "Usage recommendation: money site, PBN tier, or 301 redirect",
          "Replacement warranty certificate with a period matching your package"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Brief & Scoping",
        "desc": "You give us the details: niche, target DA/DR, language, level of clean history, and intended use (money site / PBN / 301). We lock in the criteria and budget, then start hunting. The more specific your brief, the more precise the candidates.",
        "duration": "Day 1"
      },
      {
        "step": "02",
        "title": "Research & Candidate Sourcing",
        "desc": "We comb the dropped-domain, auction, and expired markets against your criteria. A long-list of candidates is gathered and roughly filtered on initial metrics and niche relevance before they enter the deep audit.",
        "duration": "Days 2-4"
      },
      {
        "step": "03",
        "title": "History Audit & Metric Verification",
        "desc": "Every candidate goes through a forensic audit: Wayback Machine, index status, dropped records, spam score, toxic backlinks, and cross-verification of metrics across Ahrefs + Moz + Majestic. Anything inflated or carrying a dirty history gets crossed off immediately.",
        "duration": "Days 4-8"
      },
      {
        "step": "04",
        "title": "Reclaim / Registration",
        "desc": "Candidates that pass the audit get secured — reclaimed from auction or registered directly — before someone else snaps them up. Ownership is prepped to transfer into your name.",
        "duration": "Days 8-10"
      },
      {
        "step": "05",
        "title": "Complete Hand-Over",
        "desc": "Domain + audit report + raw metric data + disavow list are handed over. We guide the transfer to your registrar and give deployment recommendations. The replacement warranty starts from hand-over.",
        "duration": "Days 10-12"
      }
    ],
    "stats": [
      {
        "value": "3 tools",
        "label": "Cross-verified metrics (Ahrefs + Moz + Majestic)"
      },
      {
        "value": "100%",
        "label": "Domains get their history audited, not just the metrics"
      },
      {
        "value": "60 days",
        "label": "Maximum replacement warranty (Authority package)"
      },
      {
        "value": "0 inflated",
        "label": "PBN-pumped metrics rejected before hand-over"
      }
    ],
    "faqs": [
      {
        "q": "What's the difference between on-demand hunting and buying from an aged-domain marketplace?",
        "a": "A marketplace is ready-to-buy stock — you pick from domains that already exist, which plenty of other people may have eyed already. On-demand hunting is the opposite: we hunt from scratch to your specific brief (niche, DA/DR, language, history). The result is exclusive, custom-curated, and never resold to another client. If your need is generic and you need it fast, a marketplace will do. If you need a domain that genuinely fits your ranking targets, hunting is the answer."
      },
      {
        "q": "How do you make sure the metrics are real and not a pumped DR?",
        "a": "We don't trust a single number from a single tool. Every domain is cross-verified across Ahrefs (DR), Moz (DA), and Majestic (TF/CF). If the DR is high but the referring domains are just a link farm or the Trust Flow has tanked, that's a signal the metrics were pumped with a cheap PBN — and we cross it off immediately. You also get raw screenshot data to re-check it yourself. We will not hand over a domain with artificial metrics."
      },
      {
        "q": "What's the warranty if the metrics drop after I buy?",
        "a": "We give a replacement warranty: if the core metrics (DR/DA) drop significantly within the warranty period — 14 days (Solo), 30 days (Pro), or 60 days (Authority) — we replace it with an equivalent domain to your brief, free of charge. What's not covered: a drop caused by you spamming excessive backlinks yourself or deploying content that violates guidelines after hand-over. The warranty is about the quality of the domain at the point we hand it over, not how you use it."
      },
      {
        "q": "What does a 'clean' history actually mean? Is it guaranteed safe?",
        "a": "Clean history means we fully audit it via the Wayback Machine and dropped records: free of any ex-gambling, adult, casino, scam, or spam content that could drag down the domain's reputation. We also check index status and toxic backlinks. But honestly: 'clean at audit time' isn't an absolute guarantee that Google will never re-evaluate old history. We drive the risk as low as possible with a forensic audit — that's what we can control, and that's what we warranty."
      },
      {
        "q": "Whose name does the domain end up under? Is confidentiality safe?",
        "a": "The domain is reclaimed or registered and then handed over to become entirely yours — we guide the push/transfer to your registrar of choice. On confidentiality: the brief, niche, and domain you order are kept confidential and never displayed as portfolio. What you do with the domain after hand-over is entirely your business and your responsibility."
      },
      {
        "q": "How long does the process take from brief to receiving the domain?",
        "a": "Solo Hunt is usually 5-7 business days. Pro Hunt is 7-12 business days depending on the complexity of the brief. Authority Hunt is 12-20 business days, since high-DR or ultra-tough niches need deeper sourcing and a manual forensic audit. A very narrow niche or a high DA/DR target can add time — we give you a realistic estimate at the scoping stage, not empty promises."
      },
      {
        "q": "How does payment work?",
        "a": "Typically 50% deposit up front to start hunting, with the remaining 50% on completion once the domain passes audit and is ready for hand-over. For the Authority package or large volumes, this can be arranged per batch. We accept bank transfer and crypto (USDT) for clients who prefer it. The details are confirmed via WhatsApp at the scoping stage."
      },
      {
        "q": "Are these aged domains suitable for a long-term brand?",
        "a": "It depends on how you use them. For a money site, PBN, niche site, or 301 redirect to boost authority — these are seriously powerful. For a long-term corporate brand that wants zero risk at all, we'll be honest: aged domains always carry residual risk from their history. If you need it as clean as possible with no compromise, it's better to talk through the trade-offs with us first before you decide."
      }
    ],
    "riskNote": "Aged domains are a high-risk, high-reward strategy: old history always leaves residual risk that Google can re-evaluate at any time, which makes them better suited to money sites, PBNs, and churn-and-burn than to long-term corporate brands. We minimize the risk through a forensic audit and warranty the quality of the domain at hand-over — but the decision and the way you use it after the hand-over are entirely your responsibility."
  },
  "black-hat-seo": {
    "tagline": "Lightning-fast Google page 1 rankings. Take the risk, reap the rewards first.",
    "heroBadge": "⚡ Lightning Rankings in 7-30 Days",
    "heroTitle": "Google page 1 as fast as possible,",
    "heroTitleHighlight": "without waiting 6 months.",
    "heroSubtitle": "White-hat takes time. You need results now. The Black division at Para Suhu Digital plays aggressive: PBN networks, parasite SEO, mass indexing, and high link velocity to push your keywords to page 1 in a matter of weeks. High-risk, high-reward, and we're honest about both.",
    "intro": [
      "Did a regular agency turn down your niche? Is your industry seen as \"too gray,\" the competition brutal, or do you simply not have time to wait for conventional SEO to mature over 6-12 months? This is where the Black division plays. We take on a wide range of industries — including the ones mainstream agencies reject — and we focus on one thing: getting your keywords parked on Google page 1 as fast as aggressive techniques allow.",
      "Our approach isn't guesswork. We build and control PBN (Private Blog Network) networks with carefully maintained authority metrics, leverage parasite SEO on high-authority platforms, and run mass indexing so every link asset gets read by Google fast. Link velocity is managed strategically so ranking momentum builds in the first week, not the first quarter.",
      "But we play it straight on expectations: black-hat is high-risk, high-reward. It's a perfect fit for money sites, affiliate plays, aggressive lead-gen, and churn-and-burn strategies. If what you're after is lightning rankings and fast ROI with eyes wide open about the risks, you're in the right place. We offer a churn-and-burn option for instant results, or a more cautious long-term approach for assets you want to protect over the long haul."
    ],
    "features": [
      "Page 1 rankings in 7-30 days (depending on keyword competition)",
      "Premium PBN network with maintained DA/DR & clean footprint",
      "Parasite SEO on high-authority platforms (rank by riding big authority)",
      "Mass indexing — every backlink read by Google within hours",
      "High link velocity managed strategically for maximum momentum",
      "Niche edits & contextual link placement in relevant articles",
      "We take on a wide range of industries, including niches rejected by regular agencies",
      "Strategy options: churn-and-burn (instant) vs long-term (more durable)",
      "Daily ranking monitoring + alerts on any fluctuation",
      "Anonymity maintained — footprint and digital traces minimized"
    ],
    "packages": [
      {
        "name": "Starter Burn",
        "priceLabel": "From Rp 4.5M/month",
        "for": "Money site / churn-and-burn, 5-10 keywords low-medium competition",
        "includes": [
          "5-10 target keywords",
          "PBN links from a tier-1 network",
          "Mass indexing of all backlinks",
          "Contextual niche edits",
          "Target ranking in 14-30 days",
          "Weekly ranking monitoring",
          "Monthly keyword position report"
        ],
        "popular": false
      },
      {
        "name": "Pro Velocity",
        "priceLabel": "From Rp 12M/month",
        "for": "Serious lead-gen & affiliate, 15-30 keywords medium-high competition",
        "includes": [
          "15-30 target keywords",
          "Multi-tier PBN + parasite SEO",
          "Controlled high link velocity",
          "Priority mass indexing",
          "Niche edits + premium contextual links",
          "Target ranking in 7-21 days",
          "Daily ranking monitoring + alerts",
          "Weekly reports + strategy sessions",
          "Choice of churn-and-burn or long-term"
        ],
        "popular": true
      },
      {
        "name": "Brutal Dominate",
        "priceLabel": "Rp 30M+/month",
        "for": "Hyper-competitive niche / multi-money-site, 50+ aggressive keywords",
        "includes": [
          "50+ target keywords across domains",
          "Full dedicated PBN network + parasite stacking",
          "Maximum link velocity + anchor diversity",
          "Real-time mass indexing",
          "High-volume niche edits on high-DR sites",
          "Target ranking in 7-14 days",
          "Real-time monitoring + dedicated handler",
          "Daily reports + strategy war-room",
          "Disaster recovery plan if an update hits"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Link Assets & Network",
        "items": [
          "PBN links from a private network with maintained DA/DR",
          "Parasite SEO placement on high-authority platforms",
          "Niche edits & contextual links in relevant articles",
          "Anchor text strategy (exact, partial, branded, naked)",
          "Mass indexing report for every backlink placed"
        ]
      },
      {
        "title": "Rankings & Performance",
        "items": [
          "Position tracking for every target keyword",
          "Before-after ranking proof screenshots",
          "Traffic estimates & conversion potential per keyword",
          "Page 1 competitor analysis"
        ]
      },
      {
        "title": "Monitoring & Reporting",
        "items": [
          "Ranking monitoring dashboard (daily/weekly per package)",
          "Automatic alerts on any ranking drop",
          "Link velocity & indexing status reports",
          "Recommended next steps each period"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Audit & Risk Assessment",
        "desc": "We dissect your target keywords, competition level, and site profile. Then we set the strategy: churn-and-burn for instant results, or long-term for more durability. You get an honest picture of the risks before we start.",
        "duration": "2-3 days"
      },
      {
        "step": "02",
        "title": "Strategy & Link Mapping",
        "desc": "We draw up the blueprint: which PBN tiers, which parasite platforms, anchor text distribution, and target link velocity. Everything is designed for minimal footprint and maximum ranking momentum.",
        "duration": "3-5 days"
      },
      {
        "step": "03",
        "title": "Aggressive Execution",
        "desc": "PBN link placement, parasite SEO, and niche edits roll out at a measured velocity. Mass indexing fires immediately so Google reads it fast. This is where rankings start to move.",
        "duration": "1-3 weeks"
      },
      {
        "step": "04",
        "title": "Monitoring & Stabilization",
        "desc": "Once you hit page 1, we monitor daily, manage the remaining velocity, and keep your position stable. If there's any fluctuation, we respond right away.",
        "duration": "Ongoing"
      },
      {
        "step": "05",
        "title": "Scale or Burn",
        "desc": "For long-term, we reinforce the assets and expand keywords. For churn-and-burn, we help you maximize the harvest before the next cycle. Your strategy, your call.",
        "duration": "Per your goal"
      }
    ],
    "stats": [
      {
        "value": "7-30 days",
        "label": "Average time to reach page 1"
      },
      {
        "value": "Top 3",
        "label": "Position typically achieved for main keywords"
      },
      {
        "value": "500+",
        "label": "Keywords successfully ranked"
      },
      {
        "value": "Daily",
        "label": "Ranking monitoring & alert frequency"
      }
    ],
    "faqs": [
      {
        "q": "How fast can my keyword reach page 1?",
        "a": "It depends on the keyword's competition level. For low-medium competition, usually 7-21 days. For hyper-competitive niches, it can take 14-30 days or more. We always give you a realistic estimate at the audit stage, not empty promises."
      },
      {
        "q": "Other agencies rejected my industry. Do you take it on?",
        "a": "Most likely yes. We take on a wide range of industries, including niches that mainstream agencies consider too gray. Let's talk first at the consultation stage — we'll be honest about whether your niche is feasible and which strategy fits best."
      },
      {
        "q": "What are the real risks of black-hat SEO?",
        "a": "The main risk is a Google algorithm penalty that can drop your site's rankings or get it deindexed. That's why black-hat is best suited for money sites and churn-and-burn, not the main brand you want to protect for decades. We always spell out this risk up front and help you pick a strategy that matches your risk tolerance."
      },
      {
        "q": "Is there a ranking guarantee?",
        "a": "We guarantee effort and concrete deliverables (number of links, indexing, monitoring), not an exact position — because Google's algorithm is beyond anyone's control, including ours. What we do promise: if the target isn't met within a set period, we re-evaluate the strategy and keep optimizing at no extra cost per the package agreement."
      },
      {
        "q": "Are my identity and project kept confidential?",
        "a": "Yes. We guard our clients' anonymity strictly. We also minimize the technical footprint so traces between sites are hard to track. Specific technical details stay internal for the security of the network and our clients."
      },
      {
        "q": "What's the difference between churn-and-burn and long-term?",
        "a": "Churn-and-burn is all about instant results: fast rankings, maximum traffic/conversion harvest in a short window, then ready to swap domains if needed. Great for affiliate plays and seasonal promos. Long-term is built more carefully with subtler velocity and footprint, so the asset lasts longer. We'll help you choose based on your goal."
      },
      {
        "q": "How does payment work?",
        "a": "Monthly payment up front via bank transfer or crypto for added privacy. For the Brutal package, there's an installment option. Every agreement is laid out clearly before execution begins."
      },
      {
        "q": "What happens if my site gets penalized?",
        "a": "For the Pro and Brutal packages, we include a disaster recovery plan: root-cause analysis, asset migration, or strategy pivot. But it's important to understand — with black-hat, the penalty risk is never zero. That's why we advise against putting your main brand here."
      }
    ],
    "riskNote": "Black-hat SEO = high-risk, high-reward. These aggressive techniques can get hit with a Google algorithm penalty at any time, so they suit money sites, affiliate plays, and churn-and-burn strategies — not a long-term main brand. We're transparent about the risks; the final call is in your hands."
  },
  "black-hat-ads": {
    "tagline": "Your ads keep running, even when the product is \"hard to approve.\"",
    "heroBadge": "⚠️ High-Risk High-Reward",
    "heroTitle": "Does your product keep getting banned?",
    "heroTitleHighlight": "We're the ones who keep the ads flying.",
    "heroSubtitle": "For you selling gray-area products and tired of ad accounts dying every week: we supply trusted agency accounts, run your campaigns so they stay live, handle appeals when you get hit, and swap accounts lightning-fast the moment something goes wrong. Five platforms at once — Meta, Google, TikTok, Snack Video, Google Discovery — with one goal: your budget keeps burning in the right direction, ROAS climbs, revenue keeps flowing.",
    "intro": [
      "You already know the feeling: scaling is finally clicking, ROAS looks great, and out of nowhere the account gets disabled and all your momentum evaporates. Your product falls into a category the platforms treat as sensitive — supplements, aggressive beauty claims, financial services, gaming, or some other niche where the ad reviewers are merciless. This is where ordinary ad teams throw in the towel. We don't.",
      "The Black division of Para Suhu Digital is a dedicated unit for high-risk products. We operate on agency and trusted accounts with high limits and clean histories, run campaigns with the discipline that keeps them from getting flagged, and have backup accounts ready from day one. So when one account goes down, your campaign jumps to a fresh account within hours — not weeks.",
      "We're honest from the start: this is not a safe long-term path and we won't promise you the moon. This is the aggressive route for those who need volume fast, are willing to take the risk, and understand that in this world an account is a consumable. What we guarantee: clean execution, replacement accounts always on standby, and transparent numbers every week."
    ],
    "features": [
      "Agency & trusted accounts across 5 platforms: Meta, Google, TikTok, Snack Video, Google Discovery",
      "Full-funnel campaign setup built for products that are hard to get approved",
      "Daily management to keep campaigns live & spending stable",
      "Handling appeals when an account or ad gets flagged",
      "A pool of backup accounts ready — swap accounts fast the moment you get hit, campaign continues the same day",
      "Gradual budget scaling from hundreds of thousands up to tens of millions per day",
      "ROAS optimization: cut the losers, double down on the winners",
      "Migrating pixels, audiences & data between accounts so learning doesn't go to waste",
      "Transparent reporting: spend, ROAS, account status, remaining backup-account stock",
      "A dedicated manager on standby whenever an account suddenly goes down"
    ],
    "packages": [
      {
        "name": "Starter Burn",
        "priceLabel": "From Rp 7.5M/month",
        "for": "Testing the waters, 1 platform, small-to-medium daily budget. For you who want to validate a gray-area product before going all in.",
        "includes": [
          "1 platform of your choice (Meta / Google / TikTok / Snack Video / Discovery)",
          "1 active agency/trusted account + 1 backup account on standby",
          "Campaign setup + 3 initial creative sets",
          "Daily management & basic ROAS optimization",
          "Standard appeal handling when you get flagged",
          "Fast account swap 1x/month if one goes down",
          "Weekly report: spend, ROAS, account status"
        ],
        "popular": false
      },
      {
        "name": "Pro Scaler",
        "priceLabel": "From Rp 18M/month",
        "for": "Product already proven to convert, ready to scale seriously across 2-3 platforms at once with a daily budget in the tens of millions. Our most popular pick.",
        "includes": [
          "2-3 platforms running in parallel",
          "Pool of trusted accounts + at least 3 backup accounts per platform",
          "Full-funnel setup + regular creative rotation",
          "Daily ROAS optimization + gradual budget scaling",
          "Priority appeal handling + pixel/audience migration between accounts",
          "Unlimited fast account swaps (as long as stock is ready)",
          "Dedicated manager + reports 2x/week",
          "WhatsApp war room for rapid response when an account gets hit"
        ],
        "popular": true
      },
      {
        "name": "Brutal Mode",
        "priceLabel": "Rp 40M+/month",
        "for": "Full throttle across 5 platforms, daily budget in the tens of millions, aggressive volume targets. For money sites & large-scale churn-and-burn campaigns.",
        "includes": [
          "All 5 platforms active simultaneously",
          "Large pool of trusted accounts + backups in bulk",
          "Dedicated team (media buyer + appeal specialist + creative)",
          "Aggressive scaling up to tens of millions/day",
          "Real-time ROAS optimization + budget reallocation across platforms",
          "Highest-priority appeals + instant account replacement",
          "Multi-account & multi-domain rotation strategy",
          "Daily reports + standby 7 days/week",
          "Exit-strategy consulting before an account gets \"hot\""
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Account Infrastructure",
        "items": [
          "Agency & trusted accounts with clean histories for each platform",
          "A pool of backup accounts already warmed up and ready to use",
          "Pixel, tracking & domain verification setup per account",
          "Multi-account rotation & management so they don't drag each other down"
        ]
      },
      {
        "title": "Campaign Management & Optimization",
        "items": [
          "Full-funnel campaign setup: prospecting, retargeting, scaling",
          "Daily ROAS optimization — pause the losers, scale the winners",
          "Gradual budget scaling, from hundreds of thousands up to tens of millions/day",
          "Regular creative rotation to suppress fatigue & flag-rate"
        ]
      },
      {
        "title": "Survival & Recovery",
        "items": [
          "Handling appeals every time an account or ad gets flagged",
          "Fast account replacement — campaign moves to a new account the same day",
          "Migrating audiences, pixels & data so the learning phase doesn't go to waste",
          "Account health monitoring: estimated survival window & danger signals"
        ]
      },
      {
        "title": "Reporting & Communication",
        "items": [
          "Reporting on spend, ROAS, CPA & status of each account",
          "Updates on backup-account stock still ready to go",
          "WhatsApp war room for rapid response when an account suddenly goes down",
          "Periodic strategy reviews + recommendations on when to brake or push"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Product Audit & Risk Profiling",
        "desc": "We dissect your product, landing page, and your account history. From there we decide which platforms are most realistic, estimate how \"hot\" the product is, and how many backup accounts need to be prepared.",
        "duration": "1-3 days"
      },
      {
        "step": "02",
        "title": "Account & Infrastructure Setup",
        "desc": "We prepare agency/trusted accounts plus a backup pool, install pixels & tracking, and verify domains. Everything gets warmed up first so it doesn't get flagged the moment spending ramps up.",
        "duration": "3-7 days"
      },
      {
        "step": "03",
        "title": "Launch & Stabilization",
        "desc": "We push the full-funnel campaign with a measured budget. The focus in the first weeks: find winning creatives & audiences while keeping the account alive and stable.",
        "duration": "Week 1-2"
      },
      {
        "step": "04",
        "title": "Scaling & ROAS Optimization",
        "desc": "Once we have a profitable combination, we scale the budget gradually, reallocate to the most profitable platforms, and rotate creatives so performance doesn't sag. The target: ROAS climbing consistently without making the account heat up too fast.",
        "duration": "Ongoing"
      },
      {
        "step": "05",
        "title": "Recovery & Replace Cycle",
        "desc": "If an account gets hit, we file the appeal immediately and, in parallel, move the campaign to a backup account the same day. The goal is one thing: near-zero downtime, no break in spending momentum.",
        "duration": "Same-day response"
      }
    ],
    "stats": [
      {
        "value": "5",
        "label": "Platforms covered simultaneously"
      },
      {
        "value": "ROAS 3-7x",
        "label": "Realistic range on scaling campaigns"
      },
      {
        "value": "< 24 hrs",
        "label": "Account replacement when one goes down"
      },
      {
        "value": "Rp 50M+/day",
        "label": "Daily budget we've handled"
      }
    ],
    "faqs": [
      {
        "q": "My product gets banned all the time. Can you really keep the ads running?",
        "a": "Yes, and that's exactly our specialty. The difference isn't some instant \"secret trick\" — it's infrastructure: trusted accounts with clean histories, disciplined campaign management so they don't get flagged easily, and a pool of backup accounts always ready. So the focus isn't guaranteeing an account never dies, but making sure that the moment it does, your campaign immediately continues on another account without losing much momentum."
      },
      {
        "q": "How long can the accounts survive?",
        "a": "Honestly: it depends on the product, how aggressively you scale, and the platform. For gray-area products, an account's lifespan can run from a few weeks to a few months. That's precisely why we work on the assumption that an account = a consumable and always keep backups ready. What we optimize isn't the lifespan of a single account, but the total volume & profit you can pull before you have to move on."
      },
      {
        "q": "What ROAS is realistic?",
        "a": "A healthy range on scaling campaigns is usually 3-7x, depending on your product margin and the platform. We won't promise unrealistic double-digit ROAS. What we do: cut losing campaigns fast, double the profitable ones, and stay transparent about the numbers every week so you can do your own profit-and-loss math."
      },
      {
        "q": "If an account gets appealed, how long does recovery take?",
        "a": "We file the appeal as fast as possible, but the outcome is in the platform's hands — sometimes we win, sometimes we don't. That's why we never rely on appeals alone. The moment one account goes down, we move your campaign to a backup account the same day, so spending keeps running while the appeal is processed in parallel."
      },
      {
        "q": "Is this legal and safe for my brand?",
        "a": "This is a high-risk path. Aggressive advertising for hard-to-approve products means you accept the possibility of accounts being disabled, ads being rejected, and in certain cases penalties from the platform. We position this for money sites, dropshipping, or churn-and-burn campaigns — not for a flagship brand whose reputation you protect long-term. If you need a safe & sustainable path, we'll point you to our White division."
      },
      {
        "q": "What about confidentiality? I don't want my identity dragged into this.",
        "a": "Communication can run through private channels and we hold only as much of your data as necessary. But we're transparent: no ad service is 100% anonymous, because the platforms still have their own tracking systems. What we do is separate the campaign infrastructure from your personal assets as much as possible."
      },
      {
        "q": "How does payment work? Is there a guarantee?",
        "a": "The management fee is paid upfront per month, separate from ad spend (you cover the ad spend directly). Because this is a high-risk service, we don't offer an account-won't-die guarantee or a ROAS guarantee — those would be dishonest promises. What we do guarantee: execution per your package, replacement accounts we always work to keep ready, and transparent reporting. If you want to stop partway through, we lay it out clearly in the contract."
      },
      {
        "q": "What's the difference from regular Suhu Ads?",
        "a": "Suhu Ads (the White division) works with policy-compliant accounts & products, focused on long-term brand building and stable accounts. This Black division is specifically for gray-area products that keep getting rejected — we work on trusted accounts, prepare backups, and excel at recovery. Different risk, different goals. If you're unsure which one your product belongs in, talk to us first and we'll give you an honest recommendation."
      }
    ],
    "riskNote": "Black-hat ads = high-risk high-reward. Accounts can be disabled anytime, appeals don't always win, and platforms reserve the right to impose penalties — so this service fits money sites, dropshipping, or churn-and-burn campaigns, not a flagship brand whose reputation you protect long-term. We sell clean execution & fast recovery, not a guarantee of immortal accounts or magic ROAS."
  },
  "backlink": {
    "tagline": "Backlink power to rocket your rankings — not just to pad your numbers in Ahrefs.",
    "heroBadge": "⚡ Authority Injection — DA/DR 30-80+",
    "heroTitle": "Inject authority into your money site",
    "heroTitleHighlight": "until Google has no excuse left to hold your ranking back.",
    "heroSubtitle": "Three types of backlink, one goal: lifting your domain authority and keyword positions faster than your competitors. Hidden backlinks from authority sites, sitewide blogroll across thousands of pages, plus contextual dofollow blog posts — all on sites with clear DA/DR, high indexing rates, measurable retention, and transparent reporting. You focus on conversions, we handle the link juice.",
    "intro": [
      "Ranking on Google is an authority contest. Your competitors may already have hundreds of backlinks built over years of mileage, and you need to catch up without waiting 12 months for organic to kick in. This is exactly where aggressive backlink services come into play: we pump link juice from authority sites straight into your money site, with a structure engineered to push specific keywords up a tier.",
      "We don't sell \"1000 backlinks for Rp50K\" stuffed with comment spam and links that die a week later. What we deliver are links from sites with verified DA/DR, real traffic, and retention we guarantee in writing, black on white. Our three core products — Hidden Backlink, Blogroll, and Blogpost — each have their own character and use case, and we help you mix the right combination to match your target keywords and risk profile.",
      "Straight up from the start: this is the Black division. Our approach is high-risk, high-reward — built for money sites, competitive niches, and churn-and-burn strategies that need fast results. If you're ready to play aggressive for results that are just as aggressive, we're the right partner."
    ],
    "features": [
      "Verified authority sites at DA/DR 30-80+, not some sketchy PBN",
      "3 link types: Hidden, Blogroll, Blogpost — fully combinable",
      "Mostly dofollow, so link juice flows straight to your target",
      "85-95% indexing rate via active push indexing",
      "Link retention guaranteed 3-12 months depending on the package",
      "Natural anchor text mix: exact, partial, branded, generic",
      "Drip-feed delivery so your link velocity looks organic",
      "Full reporting: live URLs, DA/DR, index status, screenshots",
      "Topical relevance — placement sites matched to your niche",
      "Free replacement if any link drops within the guarantee window"
    ],
    "packages": [
      {
        "name": "Starter Boost",
        "priceLabel": "From Rp 1.5M",
        "for": "New money sites / light niches that need an initial authority foundation",
        "includes": [
          "10 dofollow blog posts on DA/DR 20-40 sites",
          "500+ word articles, 1 contextual link per article",
          "Natural anchor text mix",
          "Target indexing rate 85%+",
          "3-month retention guarantee",
          "Live URL + DA/DR report (Google Sheet)"
        ],
        "popular": false
      },
      {
        "name": "Pro Authority",
        "priceLabel": "From Rp 6.5M",
        "for": "Money sites in competitive niches looking to jump to page 1 fast",
        "includes": [
          "25 dofollow blog posts on DA/DR 30-60 sites",
          "5 Hidden Backlinks on authority/expired sites at DA/DR 40+",
          "1 sitewide Blogroll package (1,000+ pages) for 3 months",
          "700+ word articles, contextual dofollow",
          "Drip-fed over 3-4 weeks for natural velocity",
          "Target indexing rate 90%+, active push indexing",
          "6-month retention guarantee + free replacement on drop",
          "Monthly reporting + anchor & target keyword consultation"
        ],
        "popular": true
      },
      {
        "name": "Brutal Dominance",
        "priceLabel": "Rp 25M+",
        "for": "Gambling/finance/aggressive niches aiming to dominate the SERP & bury competitors",
        "includes": [
          "50+ dofollow blog posts on DA/DR 40-80 sites",
          "15+ Hidden Backlinks on authority/expired sites at DA/DR 50+",
          "Multi-site sitewide Blogroll (5,000+ pages) for 6 months",
          "Tiered link structure (Tier 1 + Tier 2 booster)",
          "Custom anchor & landing strategy per keyword cluster",
          "Target indexing rate 95%+ with premium indexing service",
          "12-month retention guarantee + priority replacement",
          "Dedicated account manager + bi-weekly reporting"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Hidden Backlink — hidden links on authority sites",
        "items": [
          "Links embedded in active authority sites & expired domains with high DA/DR (40-80+)",
          "Hidden placement that still gets crawled & passes link juice to your target",
          "Mostly dofollow, with exact/partial anchor text matched to your priority keywords",
          "Target indexing rate 90-95% with push indexing",
          "6-12 month retention depending on the package, with a replacement guarantee",
          "Report: host URL, DA/DR, dofollow status, index status"
        ]
      },
      {
        "title": "Blogroll — sitewide links across thousands of pages",
        "items": [
          "Links placed in the sidebar/footer so they appear sitewide across every page of the site",
          "Massive display volume: 1,000 to 5,000+ pages per site",
          "Sitewide dofollow — link equity distributed across every internal page",
          "Flexible rental duration: 3 or 6 months, extendable",
          "Ideal for lifting domain DA/DR & boosting head-term keywords",
          "Report: host domain, estimated page count, DA/DR, placement screenshots"
        ]
      },
      {
        "title": "Blogpost — quality articles + contextual dofollow",
        "items": [
          "Original 500-700+ word articles, topically relevant to your niche",
          "1 contextual dofollow link embedded naturally within the article body",
          "Placement sites at DA/DR 20-80 depending on the package, with real traffic",
          "Natural anchor text mix for a safe link profile",
          "Target indexing rate 85-95%, drip-feed delivery",
          "Report: live article URL, DA/DR, anchor, publish date"
        ]
      },
      {
        "title": "Reporting & guarantee",
        "items": [
          "Structured reporting via Google Sheet: every URL clickable & verifiable",
          "Per-link data: DA/DR, dofollow/nofollow, index status, publish date",
          "Periodic retention monitoring throughout the guarantee window",
          "Free replacement for any link that drops before the guarantee expires",
          "Anchor text & target keyword strategy consultation (Pro & Brutal packages)"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Audit & target strategy",
        "desc": "We dissect your current backlink profile, target keywords, and competitors. From there we set the link-type mix (Hidden/Blogroll/Blogpost), volume, and an anchor text plan that's safe but aggressive.",
        "duration": "1-2 days"
      },
      {
        "step": "02",
        "title": "Placement site selection",
        "desc": "We pick host sites matched to your target DA/DR, niche relevance, and real traffic. You get to preview the list of metrics before execution — no buying a pig in a poke.",
        "duration": "2-3 days"
      },
      {
        "step": "03",
        "title": "Execution & drip-feed",
        "desc": "Links are placed gradually (drip-feed) so your link velocity looks natural to Google. Articles get written, hidden links get embedded, and the blogroll goes live on the package timeline.",
        "duration": "1-4 weeks"
      },
      {
        "step": "04",
        "title": "Push indexing",
        "desc": "We push every link into the index through an active indexing service until we hit the 85-95% target rate. A link that doesn't get indexed is a wasted link, so this stage is non-negotiable.",
        "duration": "3-10 days"
      },
      {
        "step": "05",
        "title": "Reporting & retention monitoring",
        "desc": "You receive a full report with every live URL, DA/DR, index status, and screenshots. Throughout the guarantee window we monitor retention and replace any dropped link at no extra cost.",
        "duration": "Ongoing"
      }
    ],
    "stats": [
      {
        "value": "DA/DR 80+",
        "label": "Highest authority among placement sites"
      },
      {
        "value": "95%",
        "label": "Indexing rate with premium push indexing"
      },
      {
        "value": "5,000+",
        "label": "Live pages per blogroll site"
      },
      {
        "value": "12 mo",
        "label": "Maximum link retention under guarantee"
      }
    ],
    "faqs": [
      {
        "q": "What's the difference between Hidden Backlink, Blogroll, and Blogpost?",
        "a": "Hidden Backlink = a hidden link embedded in an authority site or high-DA/DR expired domain, still crawled by Google and passing link juice. Blogroll = a sitewide link in the sidebar/footer that appears across thousands of pages at once — powerful for lifting domain authority. Blogpost = a quality original article with 1 contextual dofollow link inside the body — the most natural and the safest in terms of profile. Many clients combine all three for maximum effect."
      },
      {
        "q": "Are the links dofollow or nofollow?",
        "a": "Mostly dofollow, because dofollow is what passes link equity and lifts rankings. But a healthy link profile needs a small mix of nofollow to look natural. We tune the composition automatically in every package, and the dofollow/nofollow status of each link is clearly listed in the report."
      },
      {
        "q": "How long do the links last (retention)?",
        "a": "It depends on the package: Starter guarantees 3 months, Pro 6 months, Brutal 12 months. Throughout the guarantee window, if any link drops or disappears, we replace it for free. Once the guarantee ends, you can extend the rental (blogroll only) or leave it — many blog posts and hidden links stay live far longer than their guarantee period."
      },
      {
        "q": "How high is the indexing rate?",
        "a": "Our target is 85-95% depending on the package. A link that doesn't get indexed is worth nothing, so we push every link through active push indexing until it lands in the index. You can verify each link's index status yourself in the report."
      },
      {
        "q": "Is this safe for my website? What are the risks?",
        "a": "This is a Black division service — the approach is aggressive and high-risk. Aggressive backlinks can lift rankings far faster, but there's always a risk of an algorithm update or a manual action from Google. That's why we use drip-feed, a natural anchor text mix, and real authority sites to minimize the footprint. Even so, this is best suited for money sites / churn-and-burn, not corporate brands that can't tolerate any risk at all."
      },
      {
        "q": "Are my identity and project kept confidential?",
        "a": "Yes. We maintain full confidentiality — your target URLs, keywords, and project data are never shared or used as a public portfolio without permission. Client privacy in the Black division is our baseline standard."
      },
      {
        "q": "How does payment work? Can I pay in installments?",
        "a": "For Starter and Pro, payment is upfront before execution. For Brutal Dominance, which runs over multiple months, we can arrange terms (for example 50% upfront, the rest in stages). We accept bank transfer and several other methods — details are worked out during the consultation."
      },
      {
        "q": "Is there a guarantee of ranking gains?",
        "a": "We guarantee the deliverables: number of links, site DA/DR, indexing rate, and retention as per the package — all verifiable in the report. As for ranking position, we can't promise an exact number because it's influenced by many factors beyond backlinks (on-page quality, competition, algorithms). What we do guarantee is that the authority and link juice flowing into your site are real and measurable."
      }
    ],
    "riskNote": "This is a black-hat service with a high-risk, high-reward profile: aggressive backlinks can lift rankings fast, but they still carry the risk of getting hit by a Google algorithm update or manual action. Best suited for money sites and churn-and-burn strategies, not long-term brands with zero tolerance for risk."
  },
  "landing-page": {
    "tagline": "Lightning-fast landing pages, battle-ready for your most aggressive ad campaigns.",
    "heroBadge": "⚡ Loads in <1 Second · Anti-Banned",
    "heroTitle": "AMP Landing Pages that load",
    "heroTitleHighlight": "before your thumb can even scroll.",
    "heroSubtitle": "For you, playing in expensive traffic at high volume: every 100ms of delay is money evaporating. We build ultra-light AMP-based landing pages — prelanders, money pages, A/B variants, bulletproof hosting — ready to swallow aggressive ad traffic with no sluggish loading and no pages crumbling under pressure.",
    "intro": [
      "If you're running campaigns in gambling, finance, health, or affiliate niches, you know the problem isn't just building a pretty LP. The problem: the page has to load instantly so bounce rate doesn't kill your ROAS, it has to be bulletproof so it doesn't collapse when traffic gets hot, and it has to convert ice-cold from the very first click. A normal landing page that takes 3 seconds to load? That's a budget graveyard.",
      "We focus on one thing: speed of execution and speed of the page. AMP pages that load in under 1 second, prelanders/safe pages that filter your traffic, money pages optimized to the bone for conversion, plus copywriting written to move people to take action — not to be admired. Everything mobile-first, because 90%+ of your ad traffic comes from phones.",
      "This is a high-risk, high-reward service. Perfect for money sites and churn-and-burn campaigns that need a landing page built fast, live fast, and able to hold up under pressure. We hand you a conversion machine that flat-out flies — traffic distribution strategy and platform compliance stay in your hands."
    ],
    "features": [
      "Pure AMP pages, rendering in <1 second even on a 3G connection",
      "Prelander / safe page for warming and filtering traffic quality",
      "Money page with a conversion funnel sharpened per niche",
      "High-converting copywriting: headlines, hooks, and CTAs that hit hard",
      "Bulletproof anti-banned hosting with high uptime",
      "Ready-to-use A/B variants for split-testing angles and offers",
      "100% mobile-first, passing Core Web Vitals in the green zone",
      "Tracking and pixels ready to install (Meta, TikTok, Google, custom postback)",
      "Lean structure: zero bloat, zero junk scripts",
      "Lightning deploy — your first LP can go live in a matter of days"
    ],
    "packages": [
      {
        "name": "Sprint",
        "priceLabel": "From Rp 3.5M",
        "for": "Solo affiliate / single offer that needs 1 LP live fast",
        "includes": [
          "1 conversion-optimized AMP money page",
          "Conversion copywriting (1 angle)",
          "Mobile-first responsive",
          "Basic tracking & pixel setup",
          "Guaranteed <1 second loading",
          "Standard hosting, 1 month"
        ],
        "popular": false
      },
      {
        "name": "Blitz",
        "priceLabel": "From Rp 8.5M",
        "for": "Active media buyer who needs prelander + money page + split-test",
        "includes": [
          "Prelander/safe page + money page",
          "Conversion copywriting (up to 3 angles)",
          "2 A/B variants ready to split-test",
          "Bulletproof anti-banned hosting",
          "Full tracking + affiliate postback",
          "Green Core Web Vitals + speed audit",
          "2 fast revisions within 14 days"
        ],
        "popular": true
      },
      {
        "name": "Brutal",
        "priceLabel": "Rp 25M+",
        "for": "Aggressive teams & high-volume buyers pushing many offers at once",
        "includes": [
          "Multi-LP system (prelander + multiple money pages)",
          "Unlimited-angle conversion copywriting",
          "Scalable A/B variants + testing framework",
          "Premium bulletproof hosting, multi-domain",
          "Custom funnel & tracking architecture",
          "Performance dashboard + uptime monitoring",
          "Priority deploy + fast revisions for 30 days",
          "Weekly conversion-optimization consulting"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Page Assets",
        "items": [
          "Valid AMP page file that passes the AMP test",
          "Prelander/safe page ready to go live",
          "Conversion-optimized money page",
          "Set of A/B variants per angle/offer",
          "Source files + edit access"
        ]
      },
      {
        "title": "Copy & Conversion",
        "items": [
          "Layered headlines & sub-headlines",
          "Persuasive body copy per angle",
          "Optimized CTAs & microcopy",
          "Funnel structure from hook to closing"
        ]
      },
      {
        "title": "Infrastructure & Tracking",
        "items": [
          "Bulletproof anti-banned hosting + domain pointing",
          "Pixel setup (Meta, TikTok, Google)",
          "Affiliate postback & event tracking",
          "Speed report (PageSpeed / Core Web Vitals)",
          "Deploy & variant rollover guide"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Brief & Recon",
        "desc": "We dissect the offer, niche, target traffic, and angle. You give us tracker access and assets; we draw up the LP blueprint and funnel structure.",
        "duration": "1-2 days"
      },
      {
        "step": "02",
        "title": "Copy & Conversion Design",
        "desc": "Our copywriting team crafts headlines, hooks, and CTAs. Mobile-first design is built lean, with no elements that slow it down.",
        "duration": "2-4 days"
      },
      {
        "step": "03",
        "title": "Build AMP & Set Up Hosting",
        "desc": "The page is built in pure AMP, validated, then deployed to bulletproof hosting. Tracking and pixels are installed and tested.",
        "duration": "2-3 days"
      },
      {
        "step": "04",
        "title": "Speed QA & A/B Variants",
        "desc": "We test the <1 second load across various devices, validate Core Web Vitals, and prepare A/B variants for split-testing angles.",
        "duration": "1-2 days"
      },
      {
        "step": "05",
        "title": "Go-Live & Optimization",
        "desc": "The LP goes live and is ready to swallow traffic. We monitor performance, help rotate variants, and tune conversion per your package.",
        "duration": "Ongoing"
      }
    ],
    "stats": [
      {
        "value": "<1 sec",
        "label": "LP load time on mobile"
      },
      {
        "value": "3-7 days",
        "label": "First LP live & ready to push"
      },
      {
        "value": "90+",
        "label": "Average mobile PageSpeed score"
      },
      {
        "value": "99.9%",
        "label": "Bulletproof hosting uptime"
      }
    ],
    "faqs": [
      {
        "q": "What is AMP and why does it matter for ad campaigns?",
        "a": "AMP (Accelerated Mobile Pages) is an ultra-light page format that renders almost instantly on mobile. For ad campaigns, it's crucial: the faster the LP loads, the lower the bounce rate, the higher the conversion, and the healthier your ROAS. Ad traffic is expensive — you don't want to lose clicks over slow loading."
      },
      {
        "q": "What's the difference between a prelander, a safe page, and a money page?",
        "a": "A prelander/safe page is an intermediate page for warming up traffic and filtering visitors before they hit the money page — the main page where conversion happens. Combining the two makes your funnel cleaner and your conversion numbers more stable."
      },
      {
        "q": "Is bulletproof hosting really anti-banned?",
        "a": "We use hosting infrastructure designed to be bulletproof with high uptime, well-suited to risky niches. But to be honest: nothing is 100% immune. 'Anti-banned' means far more resilient and stable than ordinary hosting, not an absolute guarantee. We're transparent about this upfront."
      },
      {
        "q": "Do you provide cloaking instructions or ways to game platform detection?",
        "a": "No. We build fast, high-converting, resilient LP assets — that's our focus. Traffic distribution strategy and compliance with platform policies are entirely your responsibility and decision as the campaign operator."
      },
      {
        "q": "Is there a conversion guarantee?",
        "a": "We guarantee the technical deliverables: <1 second load, valid AMP, mobile-first, and ready-to-use A/B variants. As for conversion numbers, those are influenced by your offer, traffic quality, and angle — what we hold up our end on is delivering the best LP machine plus a testing framework so you can optimize fast."
      },
      {
        "q": "What about anonymity and project confidentiality?",
        "a": "Confidentiality is fully protected. The details of your offer, niche, and campaign are never shared with third parties or used as a public portfolio without permission. Communication can run over encrypted channels per your preference."
      },
      {
        "q": "How does payment work? Can I pay in crypto?",
        "a": "We accept bank transfers and e-wallets. Crypto (USDT/BTC) can be arranged by agreement. Standard scheme: a deposit upfront to start the build, with the balance settled before the final LP is handed over and deployed."
      },
      {
        "q": "How fast can the LP go live?",
        "a": "The first LP is usually live within 3-7 business days, depending on the package and funnel complexity. The Brutal package gets priority deploy so you can push multiple offers faster."
      }
    ],
    "riskNote": "This service is high-risk, high-reward, designed for money sites and churn-and-burn campaigns — not long-term brands. You bear full responsibility for the legality of your offer, platform compliance, and regulations in your area of operation; we provide the technical assets, not a guarantee of results or legal advice."
  },
  "tutoring": {
    "tagline": "Learn straight from people who actually run this stuff — not stale YouTube theory.",
    "heroBadge": "🎓 1-on-1 & Group Mentoring",
    "heroTitle": "Master black-hat skills yourself",
    "heroTitleHighlight": "the kind nobody else will teach you.",
    "heroSubtitle": "Want to run ban-proof ads, aggressive SEO, or build your own backlinks and play aged domains on your own? We teach you directly, step-by-step, with material tailored to your needs and your level. Ads, SEO, backlinks, cloaking-friendly funnels — pick the topic, and we break it all down.",
    "intro": [
      "Plenty of people want to dive into black-hat but have no idea where to start — online courses are full of stale theory, groups are full of sales pitches, and the folks who actually do the work rarely open up their playbook. This is different: you learn straight from a team that runs real campaigns every single day.",
      "The material is 100% tailored. Want to focus on ban-resistant Meta Ads, parasite SEO, PBN networks, or how to read aged domain metrics so you don't get burned — just say the word. We build the curriculum around your goals, your level, and your budget. Private 1-on-1 sessions or small groups."
    ],
    "features": [
      "Tailored material: ads / SEO / backlinks / aged domains / funnels",
      "Active practitioner mentors — not pure theory",
      "1-on-1 or small group sessions (online)",
      "Real campaign & SERP case studies",
      "The templates, tools & SOPs we use ourselves",
      "Post-session Q&A group",
      "A learning roadmap built around your level & goals"
    ],
    "packages": [
      {
        "name": "Private Session",
        "priceLabel": "Contact Us",
        "for": "1-on-1, one specific topic (e.g. ban-proof Meta Ads or an aged domain audit)",
        "includes": [
          "Private 1-on-1 session (online)",
          "One focus topic of your choice",
          "Session recording + material notes",
          "7 days of post-session Q&A"
        ],
        "popular": false
      },
      {
        "name": "Monthly Mentoring",
        "priceLabel": "Contact Us",
        "for": "Ongoing guidance while you run your own projects",
        "includes": [
          "4 sessions/month (private or group)",
          "Custom curriculum built around your goals",
          "Reviews of your projects & campaigns",
          "Priority access to the Q&A group",
          "Ready-to-use templates, tools & SOPs",
          "A step-by-step learning roadmap"
        ],
        "popular": true
      },
      {
        "name": "Intensive Bootcamp",
        "priceLabel": "Contact Us",
        "for": "Go fast from zero to running it yourself, across multiple topics",
        "includes": [
          "Intensive multi-topic program (ads + SEO + backlinks)",
          "Private sessions + hands-on practice",
          "Tool & account setup alongside your mentor",
          "End-to-end case studies",
          "Guidance through your first live campaign",
          "Access to the alumni group"
        ],
        "popular": false
      }
    ],
    "deliverables": [
      {
        "title": "Material & Curriculum",
        "items": [
          "Custom curriculum built around your topic & level",
          "Slides / material docs for every session",
          "Recordings of every session",
          "Ready-to-use templates, checklists & SOPs"
        ]
      },
      {
        "title": "Guidance",
        "items": [
          "Direct reviews of your projects & accounts",
          "Post-session Q&A via the group",
          "Tool & resource recommendations",
          "An advanced learning roadmap"
        ]
      }
    ],
    "process": [
      {
        "step": "01",
        "title": "Initial Consultation",
        "desc": "Tell us your goals, your level, and the topic you want to master. We map out your needs and put together a learning plan.",
        "duration": "Day 1"
      },
      {
        "step": "02",
        "title": "Build the Curriculum",
        "desc": "We create a custom curriculum + session schedule that fits your pace. Material & tools get prepped.",
        "duration": "Days 1-3"
      },
      {
        "step": "03",
        "title": "Mentoring Sessions",
        "desc": "Learn step-by-step: the concept, a real hands-on demo, then practice on your own project.",
        "duration": "Per package"
      },
      {
        "step": "04",
        "title": "Practice & Review",
        "desc": "You execute, we review the results, correct them, and guide you until you can run on your own.",
        "duration": "Ongoing"
      }
    ],
    "stats": [
      {
        "value": "1-on-1",
        "label": "Private or small group"
      },
      {
        "value": "100%",
        "label": "Tailored material"
      },
      {
        "value": "Practitioners",
        "label": "Mentors who actually do the work"
      },
      {
        "value": "All-topic",
        "label": "Ads, SEO, backlinks, domains"
      }
    ],
    "faqs": [
      {
        "q": "What topics can you teach?",
        "a": "Anything you need: ban-proof Meta/Google/TikTok Ads, black-hat SEO (PBN, parasite, mass index), backlink techniques, how to read & audit aged domains, all the way to building cloaking-friendly funnels/landing pages. Just tell us your focus and we tailor it."
      },
      {
        "q": "Is it good for total beginners?",
        "a": "Absolutely. The curriculum is built around your level — if you're starting from zero, we begin with the fundamentals before moving up to aggressive techniques. If you're already running, we focus on optimization & scaling."
      },
      {
        "q": "Online or offline?",
        "a": "Mostly online (video call) so it's flexible and you can keep the recordings. Private sessions are scheduled by mutual agreement. Offline can be arranged on request — ask us via WhatsApp."
      },
      {
        "q": "How much does it cost?",
        "a": "It depends on the topic, the format (private/group), and the duration. Message us on WhatsApp with what you need and we'll put together an offer that fits."
      },
      {
        "q": "Do you really open up the knowledge, or hold things back?",
        "a": "We really open it up. That's exactly the difference — we break down the workflows, tools, and SOPs we use ourselves, not generic theory. The goal is for you to genuinely be able to execute on your own."
      }
    ],
    "riskNote": "Black-hat is high-risk. This mentoring teaches you the techniques plus how to manage the risk, but the decisions and responsibility for execution stay entirely in your hands."
  }
};
