// AUTO-GENERATED by scripts/gen-en-content.mjs — English proof data.
import type { Testimonial, SocialProofEvent } from "./types";

export const TESTIMONIALS_EN: Testimonial[] = [
  {
    "name": "Andre W.",
    "role": "Slot Site Owner",
    "industry": "iGaming",
    "quote": "My site broke onto page 1 for the main keyword in 19 days. Organic traffic jumped from 400 to 11K visitors a day, and what really matters, deposit conversions climbed too. This team genuinely knows how to play in brutal niches.",
    "rating": 5,
    "service": "Black Hat SEO"
  },
  {
    "name": "Rendy P.",
    "role": "Affiliate Manager",
    "industry": "Betting Affiliate",
    "quote": "The aged domain (DA 48) I bought came with a clean history and relevant backlinks. The moment I redirected it to the money site, rankings jumped without starting from scratch. Worth every rupiah.",
    "rating": 5,
    "service": "Aged Domain"
  },
  {
    "name": "Bayu S.",
    "role": "Online Herbal Store Owner",
    "industry": "Supplement E-commerce",
    "quote": "Their backlink package is a different class. 60 links from heavyweight PBNs, anchors tuned perfectly, and within 4 weeks my commercial keyword climbed 30 positions. Not a single link looked spammy.",
    "rating": 5,
    "service": "Backlink Service"
  },
  {
    "name": "Citra L.",
    "role": "Media Buyer",
    "industry": "Forex & Trading",
    "quote": "My ad campaigns kept getting banned before we worked together. Now my accounts are way more stable, CPA dropped 40%, and scaling is far safer. They were honest about the risks from day one, and that's what earned my trust.",
    "rating": 5,
    "service": "Black Hat Ads"
  },
  {
    "name": "Fajar H.",
    "role": "Sports Betting Site Owner",
    "industry": "iGaming",
    "quote": "The AMP landing page they built loads in under 1 second and has passed review again and again. Bounce rate dropped sharply, and clicks through to the sign-up page nearly doubled.",
    "rating": 5,
    "service": "AMP Landing Page"
  },
  {
    "name": "Dimas R.",
    "role": "Digital Marketer",
    "industry": "Online Loans",
    "quote": "The results were fast and measurable. They send weekly ranking reports with full detail, so I know exactly where my money is working. My fast-loan keyword hit the top 3 within a month.",
    "rating": 4,
    "service": "Black Hat SEO"
  },
  {
    "name": "Noval A.",
    "role": "Adult Site Network Owner",
    "industry": "Adult Content",
    "quote": "I manage dozens of domains and need backlinks that don't give me headaches. Their monthly package is consistent, links land every week, and rankings climb steadily with zero deindex drama.",
    "rating": 5,
    "service": "Backlink Service"
  },
  {
    "name": "Yoga T.",
    "role": "Performance Marketer",
    "industry": "Betting Affiliate",
    "quote": "The 9-year-old aged domain I picked up has high trust flow. The moment I dropped money-page content on it, Google indexed it fast and rankings stuck. The most sensible investment I've made this year.",
    "rating": 5,
    "service": "Aged Domain"
  },
  {
    "name": "Reza M.",
    "role": "Slot Site Owner",
    "industry": "iGaming",
    "quote": "I was hesitant at first because there are so many fly-by-night services. But this team was transparent, gave a clear timeline, and delivered. Revenue from organic traffic tripled in two months. Recommended for anyone serious.",
    "rating": 5,
    "service": "Black Hat SEO"
  },
  {
    "name": "Indra K.",
    "role": "Media Buyer",
    "industry": "Crypto & Trading",
    "quote": "Their black hat ads let me scale to big budgets without accounts dropping easily. CTR went up, ROAS holds consistently above 4x. Their support team is lightning-fast whenever an issue pops up.",
    "rating": 4,
    "service": "Black Hat Ads"
  },
  {
    "name": "Surya D.",
    "role": "High-Converting Landing Page Owner",
    "industry": "iGaming",
    "quote": "They completely rebuilt my old landing page into a lightweight, fast AMP version. Speed score of 98, and the biggest impact, sign-up conversions went up 70% from before.",
    "rating": 5,
    "service": "AMP Landing Page"
  },
  {
    "name": "Hendra G.",
    "role": "Freelance SEO Specialist",
    "industry": "Agency / Reseller",
    "quote": "I resell their backlink service to my own clients. Premium link quality, reasonable reseller pricing, and my clients are happy because their rankings actually move up.",
    "rating": 5,
    "service": "Backlink Service"
  }
];

export const SOCIAL_PROOF_EN: SocialProofEvent[] = [
  {
    "name": "Budi S.",
    "city": "Jakarta",
    "action": "just bought a DA 42 aged domain",
    "timeAgo": "2 minutes ago"
  },
  {
    "name": "Rina W.",
    "city": "Surabaya",
    "action": "ordered the Black Hat SEO Pro package",
    "timeAgo": "5 minutes ago"
  },
  {
    "name": "Doni P.",
    "city": "Bandung",
    "action": "grabbed 50 blogpost backlinks",
    "timeAgo": "8 minutes ago"
  },
  {
    "name": "Agus T.",
    "city": "Medan",
    "action": "ordered an AMP Slot Landing Page",
    "timeAgo": "12 minutes ago"
  },
  {
    "name": "Sari M.",
    "city": "Bekasi",
    "action": "upgraded to the Black Hat Ads Scaling package",
    "timeAgo": "15 minutes ago"
  },
  {
    "name": "Fikri R.",
    "city": "Tangerang",
    "action": "bought an 8-year-old aged domain",
    "timeAgo": "21 minutes ago"
  },
  {
    "name": "Wawan H.",
    "city": "Semarang",
    "action": "ordered the 100-link PBN Backlink package",
    "timeAgo": "27 minutes ago"
  },
  {
    "name": "Lia K.",
    "city": "Depok",
    "action": "grabbed the Black Hat SEO Starter package",
    "timeAgo": "34 minutes ago"
  },
  {
    "name": "Yusuf A.",
    "city": "Makassar",
    "action": "ordered 30 premium dofollow backlinks",
    "timeAgo": "42 minutes ago"
  },
  {
    "name": "Galih N.",
    "city": "Yogyakarta",
    "action": "bought 3 aged domains at once",
    "timeAgo": "51 minutes ago"
  },
  {
    "name": "Putra D.",
    "city": "Palembang",
    "action": "ordered an AMP Sports Betting Landing Page",
    "timeAgo": "1 hour ago"
  },
  {
    "name": "Nanda S.",
    "city": "Bogor",
    "action": "upgraded the Black Hat SEO Pro package",
    "timeAgo": "1 hour ago"
  },
  {
    "name": "Eko B.",
    "city": "Malang",
    "action": "grabbed the monthly Backlink package",
    "timeAgo": "2 hours ago"
  },
  {
    "name": "Vina L.",
    "city": "Denpasar",
    "action": "ordered the Black Hat Ads Forex package",
    "timeAgo": "2 hours ago"
  },
  {
    "name": "Rizal F.",
    "city": "Batam",
    "action": "bought a DA 55 high trust flow aged domain",
    "timeAgo": "3 hours ago"
  },
  {
    "name": "Hana P.",
    "city": "Pekanbaru",
    "action": "ordered the SEO + Backlink combo package",
    "timeAgo": "3 hours ago"
  }
];
