// AUTO-GENERATED by scripts/gen-content.mjs — do not edit by hand.
import type { Testimonial, SocialProofEvent } from "./types";

export const TESTIMONIALS: Testimonial[] = [
  {
    "name": "Andre W.",
    "role": "Owner Situs Slot",
    "industry": "iGaming",
    "quote": "Site gua nembus page 1 buat keyword utama dalam 19 hari. Trafik organik naik dari 400 jadi 11rb visitor per hari, dan yang penting konversi deposit ikut naik. Tim ini ngerti banget cara main di niche keras.",
    "rating": 5,
    "service": "Black Hat SEO"
  },
  {
    "name": "Rendy P.",
    "role": "Affiliate Manager",
    "industry": "Betting Affiliate",
    "quote": "Aged domain DA 48 yang gua beli langsung punya histori bersih dan backlink relevan. Begitu di-redirect ke money site, ranking lompat tanpa harus mulai dari nol. Worth tiap rupiah.",
    "rating": 5,
    "service": "Aged Domain"
  },
  {
    "name": "Bayu S.",
    "role": "Owner Toko Herbal Online",
    "industry": "E-commerce Suplemen",
    "quote": "Paket backlink mereka beda kelas. 60 link dari PBN kelas berat, anchor diatur rapi, dan dalam 4 minggu keyword komersil gua naik 30 posisi. Gak ada satupun link yang keliatan spammy.",
    "rating": 5,
    "service": "Jasa Backlink"
  },
  {
    "name": "Citra L.",
    "role": "Media Buyer",
    "industry": "Forex & Trading",
    "quote": "Campaign ads gua sering kena banned sebelum kerja sama. Sekarang akun lebih stabil, CPA turun 40%, dan scaling-nya jauh lebih aman. Mereka jujur soal risiko dari awal, itu yang bikin gua percaya.",
    "rating": 5,
    "service": "Black Hat Ads"
  },
  {
    "name": "Fajar H.",
    "role": "Owner Situs Judi Bola",
    "industry": "iGaming",
    "quote": "Landing page AMP buatan mereka loading di bawah 1 detik dan lolos review berkali-kali. Bounce rate turun drastis, dan angka klik ke halaman daftar naik hampir dua kali lipat.",
    "rating": 5,
    "service": "Landing Page AMP"
  },
  {
    "name": "Dimas R.",
    "role": "Digital Marketer",
    "industry": "Pinjaman Online",
    "quote": "Hasilnya cepat dan terukur. Mereka kasih laporan ranking mingguan plingkap, jadi gua tahu persis uang gua kerja di mana. Keyword pinjaman cepat masuk top 3 dalam sebulan.",
    "rating": 4,
    "service": "Black Hat SEO"
  },
  {
    "name": "Noval A.",
    "role": "Owner Network Situs Dewasa",
    "industry": "Adult Content",
    "quote": "Gua kelola puluhan domain dan butuh backlink yang gak bikin pusing. Paket bulanan mereka konsisten, link masuk tiap minggu, ranking naik stabil tanpa drama deindex.",
    "rating": 5,
    "service": "Jasa Backlink"
  },
  {
    "name": "Yoga T.",
    "role": "Performance Marketer",
    "industry": "Betting Affiliate",
    "quote": "Aged domain umur 9 tahun yang gua ambil punya trust flow tinggi. Begitu dipasang konten money page, indeks Google langsung cepat dan ranking nempel. Investasi paling masuk akal tahun ini.",
    "rating": 5,
    "service": "Aged Domain"
  },
  {
    "name": "Reza M.",
    "role": "Owner Situs Slot",
    "industry": "iGaming",
    "quote": "Sempat ragu karena banyak jasa abal-abal. Tapi tim ini transparan, ngasih timeline jelas, dan deliver. Omzet dari trafik organik naik 3x lipat dalam dua bulan. Recommended buat yang serius.",
    "rating": 5,
    "service": "Black Hat SEO"
  },
  {
    "name": "Indra K.",
    "role": "Media Buyer",
    "industry": "Crypto & Trading",
    "quote": "Black hat ads mereka bikin gua bisa scaling ke budget gede tanpa akun gampang tumbang. CTR naik, ROAS konsisten di atas 4x. Tim support-nya juga gercep tiap ada kendala.",
    "rating": 4,
    "service": "Black Hat Ads"
  },
  {
    "name": "Surya D.",
    "role": "Owner Landing Page Gacor",
    "industry": "iGaming",
    "quote": "Mereka rombak total landing page lama gua jadi versi AMP yang ringan dan cepat. Speed score 98, dan yang paling kerasa, konversi pendaftaran naik 70% dari sebelumnya.",
    "rating": 5,
    "service": "Landing Page AMP"
  },
  {
    "name": "Hendra G.",
    "role": "SEO Specialist Freelance",
    "industry": "Agency / Reseller",
    "quote": "Gua reseller jasa backlink mereka ke klien-klien gua. Kualitas link premium, harga reseller masuk akal, dan klien gua puas karena ranking mereka beneran gerak naik.",
    "rating": 5,
    "service": "Jasa Backlink"
  }
];

export const SOCIAL_PROOF: SocialProofEvent[] = [
  {
    "name": "Budi S.",
    "city": "Jakarta",
    "action": "baru beli aged domain DA 42",
    "timeAgo": "2 menit lalu"
  },
  {
    "name": "Rina W.",
    "city": "Surabaya",
    "action": "order paket Black Hat SEO Pro",
    "timeAgo": "5 menit lalu"
  },
  {
    "name": "Doni P.",
    "city": "Bandung",
    "action": "ambil 50 blogpost backlink",
    "timeAgo": "8 menit lalu"
  },
  {
    "name": "Agus T.",
    "city": "Medan",
    "action": "order Landing Page AMP Slot",
    "timeAgo": "12 menit lalu"
  },
  {
    "name": "Sari M.",
    "city": "Bekasi",
    "action": "upgrade ke paket Black Hat Ads Scaling",
    "timeAgo": "15 menit lalu"
  },
  {
    "name": "Fikri R.",
    "city": "Tangerang",
    "action": "beli aged domain umur 8 tahun",
    "timeAgo": "21 menit lalu"
  },
  {
    "name": "Wawan H.",
    "city": "Semarang",
    "action": "order paket Backlink PBN 100 link",
    "timeAgo": "27 menit lalu"
  },
  {
    "name": "Lia K.",
    "city": "Depok",
    "action": "ambil paket Black Hat SEO Starter",
    "timeAgo": "34 menit lalu"
  },
  {
    "name": "Yusuf A.",
    "city": "Makassar",
    "action": "order 30 backlink dofollow premium",
    "timeAgo": "42 menit lalu"
  },
  {
    "name": "Galih N.",
    "city": "Yogyakarta",
    "action": "beli 3 aged domain sekaligus",
    "timeAgo": "51 menit lalu"
  },
  {
    "name": "Putra D.",
    "city": "Palembang",
    "action": "order Landing Page AMP Bola",
    "timeAgo": "1 jam lalu"
  },
  {
    "name": "Nanda S.",
    "city": "Bogor",
    "action": "upgrade paket Black Hat SEO Pro",
    "timeAgo": "1 jam lalu"
  },
  {
    "name": "Eko B.",
    "city": "Malang",
    "action": "ambil paket Backlink bulanan",
    "timeAgo": "2 jam lalu"
  },
  {
    "name": "Vina L.",
    "city": "Denpasar",
    "action": "order paket Black Hat Ads Forex",
    "timeAgo": "2 jam lalu"
  },
  {
    "name": "Rizal F.",
    "city": "Batam",
    "action": "beli aged domain DA 55 trust flow tinggi",
    "timeAgo": "3 jam lalu"
  },
  {
    "name": "Hana P.",
    "city": "Pekanbaru",
    "action": "order paket SEO + Backlink combo",
    "timeAgo": "3 jam lalu"
  }
];
